import type { InsertRunningShoe } from "@shared/schema";

export const shoeData: InsertRunningShoe[] = [
  // NIKE
  {
    brand: "Nike",
    model: "Pegasus 41",
    category: "daily_trainer",
    weight: 10.0,
    heelStackHeight: 37,
    forefootStackHeight: 27,
    heelToToeDrop: 10,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 140,
    bestFor: ["easy_runs", "long_runs", "tempo"],
    minRunnerWeight: 120,
    maxRunnerWeight: 220,
    durabilityRating: 4.2,
    responsivenessRating: 3.8,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "The workhorse daily trainer with ReactX foam and dual Air Zoom units. Versatile for all training types."
  },
  {
    brand: "Nike",
    model: "Vaporfly 3",
    category: "racing",
    weight: 6.5,
    heelStackHeight: 40,
    forefootStackHeight: 32,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 260,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 180,
    durabilityRating: 2.5,
    responsivenessRating: 5.0,
    comfortRating: 3.8,
    releaseYear: 2023,
    description: "Elite marathon racing shoe with ZoomX foam and carbon plate. Maximum energy return."
  },
  {
    brand: "Nike",
    model: "Alphafly 3",
    category: "racing",
    weight: 7.0,
    heelStackHeight: 40,
    forefootStackHeight: 32,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 285,
    bestFor: ["racing"],
    minRunnerWeight: 100,
    maxRunnerWeight: 170,
    durabilityRating: 2.5,
    responsivenessRating: 5.0,
    comfortRating: 3.8,
    releaseYear: 2024,
    description: "Nike's lightest, most aggressive marathon racer with ZoomX foam, dual Air Zoom pods, and widened carbon Flyplate."
  },
  {
    brand: "Nike",
    model: "Alphafly 2",
    category: "racing",
    weight: 8.0,
    heelStackHeight: 40,
    forefootStackHeight: 32,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 275,
    bestFor: ["racing"],
    minRunnerWeight: 100,
    maxRunnerWeight: 180,
    durabilityRating: 2.5,
    responsivenessRating: 4.8,
    comfortRating: 3.5,
    releaseYear: 2022,
    description: "Second generation Alphafly with wider platform, improved stability, and ZoomX foam under the Air Zoom units."
  },
  {
    brand: "Nike",
    model: "Alphafly NEXT%",
    category: "racing",
    weight: 7.4,
    heelStackHeight: 40,
    forefootStackHeight: 36,
    heelToToeDrop: 4,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing"],
    minRunnerWeight: 100,
    maxRunnerWeight: 170,
    durabilityRating: 2.0,
    responsivenessRating: 5.0,
    comfortRating: 3.5,
    releaseYear: 2020,
    description: "The original super shoe that changed marathon racing. ZoomX foam, carbon plate, and dual Air Zoom pods."
  },
  {
    brand: "Nike",
    model: "Vaporfly Next% 2",
    category: "racing",
    weight: 6.9,
    heelStackHeight: 40,
    forefootStackHeight: 32,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 180,
    durabilityRating: 2.5,
    responsivenessRating: 5.0,
    comfortRating: 3.8,
    releaseYear: 2021,
    description: "Updated Vaporfly with improved mesh upper while maintaining the legendary ZoomX and carbon plate combination."
  },
  {
    brand: "Nike",
    model: "Invincible 3",
    category: "recovery",
    weight: 10.6,
    heelStackHeight: 37,
    forefootStackHeight: 28,
    heelToToeDrop: 9,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 180,
    bestFor: ["easy_runs", "recovery"],
    minRunnerWeight: 140,
    maxRunnerWeight: 250,
    durabilityRating: 3.5,
    responsivenessRating: 3.0,
    comfortRating: 5.0,
    releaseYear: 2023,
    description: "Maximum cushioned recovery shoe with plush ZoomX foam for easy days."
  },
  {
    brand: "Nike",
    model: "Vomero 18",
    category: "daily_trainer",
    weight: 10.9,
    heelStackHeight: 36,
    forefootStackHeight: 26,
    heelToToeDrop: 10,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 160,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 230,
    durabilityRating: 4.0,
    responsivenessRating: 3.5,
    comfortRating: 4.8,
    releaseYear: 2024,
    description: "Premium cushioned daily trainer with ZoomX midsole for comfortable miles."
  },
  {
    brand: "Nike",
    model: "Structure 25",
    category: "daily_trainer",
    weight: 10.2,
    heelStackHeight: 35,
    forefootStackHeight: 25,
    heelToToeDrop: 10,
    cushioningLevel: "medium",
    stability: "mild_stability",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 140,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 230,
    durabilityRating: 4.2,
    responsivenessRating: 3.5,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Stability trainer with Dynamic Support System for overpronators. ReactX foam midsole."
  },
  // BROOKS
  {
    brand: "Brooks",
    model: "Ghost 16",
    category: "daily_trainer",
    weight: 9.8,
    heelStackHeight: 36,
    forefootStackHeight: 24,
    heelToToeDrop: 12,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 140,
    bestFor: ["easy_runs", "long_runs", "tempo"],
    minRunnerWeight: 130,
    maxRunnerWeight: 220,
    durabilityRating: 4.5,
    responsivenessRating: 3.5,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "Smooth, balanced daily trainer with DNA LOFT v3 cushioning. A true workhorse."
  },
  {
    brand: "Brooks",
    model: "Glycerin 21",
    category: "long_run",
    weight: 10.6,
    heelStackHeight: 38,
    forefootStackHeight: 28,
    heelToToeDrop: 10,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 160,
    bestFor: ["long_runs", "easy_runs", "recovery"],
    minRunnerWeight: 150,
    maxRunnerWeight: 240,
    durabilityRating: 4.2,
    responsivenessRating: 3.2,
    comfortRating: 5.0,
    releaseYear: 2024,
    description: "Max cushion daily trainer with plush GlycerinHD foam. Ideal for long runs."
  },
  {
    brand: "Brooks",
    model: "Hyperion Elite 3",
    category: "racing",
    weight: 7.0,
    heelStackHeight: 39.5,
    forefootStackHeight: 31.5,
    heelToToeDrop: 8,
    cushioningLevel: "firm",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 2.5,
    responsivenessRating: 4.8,
    comfortRating: 3.5,
    releaseYear: 2023,
    description: "Elite carbon racing shoe with DNA FLASH midsole for race day performance."
  },
  {
    brand: "Brooks",
    model: "Adrenaline GTS 24",
    category: "daily_trainer",
    weight: 10.4,
    heelStackHeight: 36,
    forefootStackHeight: 24,
    heelToToeDrop: 12,
    cushioningLevel: "medium",
    stability: "mild_stability",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 140,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 130,
    maxRunnerWeight: 230,
    durabilityRating: 4.5,
    responsivenessRating: 3.3,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Stability trainer with GuideRails holistic support system. Great for overpronators."
  },
  {
    brand: "Brooks",
    model: "Ghost Max 2",
    category: "recovery",
    weight: 10.9,
    heelStackHeight: 39,
    forefootStackHeight: 33,
    heelToToeDrop: 6,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 160,
    bestFor: ["easy_runs", "recovery", "long_runs"],
    minRunnerWeight: 150,
    maxRunnerWeight: 250,
    durabilityRating: 4.0,
    responsivenessRating: 3.0,
    comfortRating: 4.8,
    releaseYear: 2024,
    description: "Maximum cushioned version of the Ghost with DNA LOFT v2 and nitrogen-infused foam."
  },
  // HOKA
  {
    brand: "Hoka",
    model: "Clifton 9",
    category: "daily_trainer",
    weight: 8.7,
    heelStackHeight: 32,
    forefootStackHeight: 27,
    heelToToeDrop: 5,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 145,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 120,
    maxRunnerWeight: 200,
    durabilityRating: 3.8,
    responsivenessRating: 3.5,
    comfortRating: 4.8,
    releaseYear: 2023,
    description: "Lightweight cushioned trainer with signature Hoka marshmallow feel. ProFly+ midsole."
  },
  {
    brand: "Hoka",
    model: "Bondi 8",
    category: "recovery",
    weight: 10.8,
    heelStackHeight: 37,
    forefootStackHeight: 33,
    heelToToeDrop: 4,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 165,
    bestFor: ["easy_runs", "recovery", "long_runs"],
    minRunnerWeight: 150,
    maxRunnerWeight: 260,
    durabilityRating: 4.0,
    responsivenessRating: 2.8,
    comfortRating: 5.0,
    releaseYear: 2023,
    description: "Maximum cushioned shoe for high mileage and recovery runs. Ultra plush EVA foam."
  },
  {
    brand: "Hoka",
    model: "Mach 6",
    category: "speed_training",
    weight: 7.9,
    heelStackHeight: 35,
    forefootStackHeight: 30,
    heelToToeDrop: 5,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 140,
    bestFor: ["tempo", "speed_work", "racing"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 3.5,
    responsivenessRating: 4.5,
    comfortRating: 4.0,
    releaseYear: 2024,
    description: "Light and fast tempo trainer with PEBA foam. Great for uptempo workouts."
  },
  {
    brand: "Hoka",
    model: "Rocket X 2",
    category: "racing",
    weight: 7.4,
    heelStackHeight: 39,
    forefootStackHeight: 34,
    heelToToeDrop: 5,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 175,
    durabilityRating: 2.5,
    responsivenessRating: 4.8,
    comfortRating: 3.8,
    releaseYear: 2023,
    description: "Carbon-plated race day shoe with PEBA foam for maximum speed."
  },
  {
    brand: "Hoka",
    model: "Arahi 7",
    category: "daily_trainer",
    weight: 9.5,
    heelStackHeight: 35,
    forefootStackHeight: 30,
    heelToToeDrop: 5,
    cushioningLevel: "medium",
    stability: "mild_stability",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 150,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 130,
    maxRunnerWeight: 220,
    durabilityRating: 4.0,
    responsivenessRating: 3.5,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Stability shoe with J-Frame technology for mild overpronation support."
  },
  {
    brand: "Hoka",
    model: "Skyward X",
    category: "long_run",
    weight: 10.2,
    heelStackHeight: 40,
    forefootStackHeight: 35,
    heelToToeDrop: 5,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 225,
    bestFor: ["long_runs", "easy_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 230,
    durabilityRating: 3.8,
    responsivenessRating: 4.2,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "Max stack daily trainer with carbon fiber plate and PEBA foam for long training runs."
  },
  // ASICS
  {
    brand: "Asics",
    model: "Gel-Nimbus 26",
    category: "long_run",
    weight: 10.7,
    heelStackHeight: 42,
    forefootStackHeight: 34,
    heelToToeDrop: 8,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 160,
    bestFor: ["long_runs", "easy_runs", "recovery"],
    minRunnerWeight: 150,
    maxRunnerWeight: 250,
    durabilityRating: 4.2,
    responsivenessRating: 3.2,
    comfortRating: 4.8,
    releaseYear: 2024,
    description: "Premium neutral cushioned shoe with FF BLAST PLUS ECO foam and PureGel technology."
  },
  {
    brand: "Asics",
    model: "Gel-Kayano 31",
    category: "daily_trainer",
    weight: 11.0,
    heelStackHeight: 40,
    forefootStackHeight: 27,
    heelToToeDrop: 13,
    cushioningLevel: "medium",
    stability: "motion_control",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 160,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 160,
    maxRunnerWeight: 260,
    durabilityRating: 4.5,
    responsivenessRating: 3.0,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Premium stability shoe with 4D Guidance System for maximum support."
  },
  {
    brand: "Asics",
    model: "Novablast 4",
    category: "daily_trainer",
    weight: 9.2,
    heelStackHeight: 37,
    forefootStackHeight: 29,
    heelToToeDrop: 8,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 140,
    bestFor: ["easy_runs", "long_runs", "tempo"],
    minRunnerWeight: 120,
    maxRunnerWeight: 200,
    durabilityRating: 3.8,
    responsivenessRating: 4.2,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "Bouncy daily trainer with FF BLAST PLUS foam for energetic rides."
  },
  {
    brand: "Asics",
    model: "Metaspeed Sky Paris",
    category: "racing",
    weight: 6.7,
    heelStackHeight: 39.5,
    forefootStackHeight: 34.5,
    heelToToeDrop: 5,
    cushioningLevel: "firm",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing"],
    minRunnerWeight: 100,
    maxRunnerWeight: 170,
    durabilityRating: 2.0,
    responsivenessRating: 5.0,
    comfortRating: 3.5,
    releaseYear: 2024,
    description: "Elite marathon racing shoe with FF TURBO PLUS foam and carbon plate for stride runners."
  },
  {
    brand: "Asics",
    model: "Magic Speed 4",
    category: "speed_training",
    weight: 7.4,
    heelStackHeight: 36,
    forefootStackHeight: 31,
    heelToToeDrop: 5,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 180,
    bestFor: ["tempo", "speed_work", "racing"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 3.2,
    responsivenessRating: 4.5,
    comfortRating: 3.8,
    releaseYear: 2024,
    description: "Affordable carbon racer for workouts and shorter races."
  },
  {
    brand: "Asics",
    model: "Superblast 2",
    category: "speed_training",
    weight: 8.2,
    heelStackHeight: 39,
    forefootStackHeight: 34,
    heelToToeDrop: 5,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 200,
    bestFor: ["tempo", "speed_work", "long_runs"],
    minRunnerWeight: 120,
    maxRunnerWeight: 190,
    durabilityRating: 3.5,
    responsivenessRating: 4.6,
    comfortRating: 4.2,
    releaseYear: 2024,
    description: "Premium training shoe with FF TURBO PLUS foam. Marathon trainer without carbon plate."
  },
  // NEW BALANCE
  {
    brand: "New Balance",
    model: "Fresh Foam X 1080v14",
    category: "daily_trainer",
    weight: 10.4,
    heelStackHeight: 38,
    forefootStackHeight: 32,
    heelToToeDrop: 6,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 165,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 230,
    durabilityRating: 4.0,
    responsivenessRating: 3.5,
    comfortRating: 4.8,
    releaseYear: 2024,
    description: "Premium cushioned trainer with Fresh Foam X midsole. All-day comfort."
  },
  {
    brand: "New Balance",
    model: "Fresh Foam X More v5",
    category: "recovery",
    weight: 11.6,
    heelStackHeight: 38,
    forefootStackHeight: 34,
    heelToToeDrop: 4,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 175,
    bestFor: ["easy_runs", "recovery"],
    minRunnerWeight: 160,
    maxRunnerWeight: 280,
    durabilityRating: 4.2,
    responsivenessRating: 2.8,
    comfortRating: 5.0,
    releaseYear: 2024,
    description: "Maximum cushioned recovery shoe with ultra-plush Fresh Foam X."
  },
  {
    brand: "New Balance",
    model: "FuelCell SuperComp Elite v4",
    category: "racing",
    weight: 7.0,
    heelStackHeight: 39.5,
    forefootStackHeight: 31.5,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 230,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 175,
    durabilityRating: 2.5,
    responsivenessRating: 4.8,
    comfortRating: 3.6,
    releaseYear: 2024,
    description: "Elite carbon racer with FuelCell foam for race day performance."
  },
  {
    brand: "New Balance",
    model: "FuelCell Rebel v4",
    category: "speed_training",
    weight: 7.8,
    heelStackHeight: 30,
    forefootStackHeight: 24,
    heelToToeDrop: 6,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 140,
    bestFor: ["tempo", "speed_work", "easy_runs"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 3.5,
    responsivenessRating: 4.5,
    comfortRating: 4.2,
    releaseYear: 2024,
    description: "Light, fast, and fun trainer for uptempo workouts and daily runs."
  },
  {
    brand: "New Balance",
    model: "FuelCell Propel v5",
    category: "daily_trainer",
    weight: 9.6,
    heelStackHeight: 32,
    forefootStackHeight: 26,
    heelToToeDrop: 6,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 110,
    bestFor: ["easy_runs", "tempo"],
    minRunnerWeight: 120,
    maxRunnerWeight: 200,
    durabilityRating: 4.0,
    responsivenessRating: 4.0,
    comfortRating: 4.0,
    releaseYear: 2024,
    description: "Affordable FuelCell trainer for responsive daily miles."
  },
  {
    brand: "New Balance",
    model: "FuelCell SC Trainer v3",
    category: "speed_training",
    weight: 8.8,
    heelStackHeight: 37,
    forefootStackHeight: 29,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 190,
    bestFor: ["tempo", "speed_work", "long_runs"],
    minRunnerWeight: 120,
    maxRunnerWeight: 195,
    durabilityRating: 3.5,
    responsivenessRating: 4.3,
    comfortRating: 4.0,
    releaseYear: 2024,
    description: "Carbon plated training shoe for high-intensity workouts. Durable race day trainer."
  },
  // SAUCONY
  {
    brand: "Saucony",
    model: "Ride 17",
    category: "daily_trainer",
    weight: 9.5,
    heelStackHeight: 35,
    forefootStackHeight: 27,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 140,
    bestFor: ["easy_runs", "long_runs", "tempo"],
    minRunnerWeight: 130,
    maxRunnerWeight: 210,
    durabilityRating: 4.2,
    responsivenessRating: 3.8,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "Versatile PWRRUN+ trainer for everyday miles. Smooth and reliable."
  },
  {
    brand: "Saucony",
    model: "Triumph 22",
    category: "long_run",
    weight: 10.2,
    heelStackHeight: 38,
    forefootStackHeight: 28,
    heelToToeDrop: 10,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 160,
    bestFor: ["long_runs", "easy_runs", "recovery"],
    minRunnerWeight: 150,
    maxRunnerWeight: 240,
    durabilityRating: 4.0,
    responsivenessRating: 3.3,
    comfortRating: 4.8,
    releaseYear: 2024,
    description: "Max cushioned trainer with PWRRUN PB foam for plush, long runs."
  },
  {
    brand: "Saucony",
    model: "Endorphin Pro 4",
    category: "racing",
    weight: 7.7,
    heelStackHeight: 40,
    forefootStackHeight: 32,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 225,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 175,
    durabilityRating: 2.5,
    responsivenessRating: 4.9,
    comfortRating: 3.6,
    releaseYear: 2024,
    description: "Elite carbon racer with dual-density PWRRUN HG + PWRRUN PB foam for race day speed."
  },
  {
    brand: "Saucony",
    model: "Endorphin Speed 4",
    category: "speed_training",
    weight: 7.8,
    heelStackHeight: 38,
    forefootStackHeight: 30,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 170,
    bestFor: ["tempo", "speed_work", "racing"],
    minRunnerWeight: 110,
    maxRunnerWeight: 185,
    durabilityRating: 3.5,
    responsivenessRating: 4.5,
    comfortRating: 4.0,
    releaseYear: 2024,
    description: "Nylon plate tempo trainer with PWRRUN PB foam. Great for workouts and races."
  },
  {
    brand: "Saucony",
    model: "Kinvara 15",
    category: "speed_training",
    weight: 7.5,
    heelStackHeight: 28,
    forefootStackHeight: 24,
    heelToToeDrop: 4,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 130,
    bestFor: ["tempo", "speed_work", "easy_runs"],
    minRunnerWeight: 100,
    maxRunnerWeight: 170,
    durabilityRating: 3.5,
    responsivenessRating: 4.2,
    comfortRating: 4.0,
    releaseYear: 2024,
    description: "Light and natural feeling trainer for fast, minimal miles."
  },
  {
    brand: "Saucony",
    model: "Guide 17",
    category: "daily_trainer",
    weight: 10.1,
    heelStackHeight: 35,
    forefootStackHeight: 27,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "mild_stability",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 140,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 230,
    durabilityRating: 4.3,
    responsivenessRating: 3.5,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Stability trainer with medial TPU guidance frame for overpronation support."
  },
  // ON
  {
    brand: "On",
    model: "Cloudmonster 2",
    category: "daily_trainer",
    weight: 10.4,
    heelStackHeight: 35,
    forefootStackHeight: 29,
    heelToToeDrop: 6,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 180,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 220,
    durabilityRating: 4.0,
    responsivenessRating: 3.8,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Max cushioned CloudTec trainer with dual-density Helion foam and Speedboard."
  },
  {
    brand: "On",
    model: "Cloudsurfer 7",
    category: "daily_trainer",
    weight: 9.5,
    heelStackHeight: 32,
    forefootStackHeight: 25,
    heelToToeDrop: 7,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 160,
    bestFor: ["easy_runs", "tempo"],
    minRunnerWeight: 120,
    maxRunnerWeight: 200,
    durabilityRating: 3.8,
    responsivenessRating: 4.0,
    comfortRating: 4.2,
    releaseYear: 2024,
    description: "Versatile trainer with CloudTec Phase cushioning system."
  },
  {
    brand: "On",
    model: "Cloudboom Echo 3",
    category: "racing",
    weight: 7.8,
    heelStackHeight: 39,
    forefootStackHeight: 33,
    heelToToeDrop: 6,
    cushioningLevel: "firm",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 290,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 175,
    durabilityRating: 2.5,
    responsivenessRating: 4.7,
    comfortRating: 3.5,
    releaseYear: 2023,
    description: "Elite carbon racer with Helion HF superfoam and Speedboard."
  },
  {
    brand: "On",
    model: "Cloudflow 4",
    category: "speed_training",
    weight: 8.1,
    heelStackHeight: 28,
    forefootStackHeight: 22,
    heelToToeDrop: 6,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 160,
    bestFor: ["tempo", "speed_work", "racing"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 3.5,
    responsivenessRating: 4.2,
    comfortRating: 3.8,
    releaseYear: 2023,
    description: "Lightweight performance trainer with Helion foam and Speedboard for fast workouts."
  },
  {
    brand: "On",
    model: "Cloudrunner 2",
    category: "daily_trainer",
    weight: 10.1,
    heelStackHeight: 33,
    forefootStackHeight: 23,
    heelToToeDrop: 10,
    cushioningLevel: "medium",
    stability: "mild_stability",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 150,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 230,
    durabilityRating: 4.2,
    responsivenessRating: 3.5,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Supportive daily trainer with CloudTec pods and medial guidance for mild stability."
  },
  // ALTRA (Zero Drop)
  {
    brand: "Altra",
    model: "Torin 7",
    category: "daily_trainer",
    weight: 9.8,
    heelStackHeight: 30,
    forefootStackHeight: 30,
    heelToToeDrop: 0,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 150,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 130,
    maxRunnerWeight: 210,
    durabilityRating: 4.0,
    responsivenessRating: 3.2,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "Zero-drop cushioned trainer with Altra EGO MAX foam and wide FootShape toe box."
  },
  {
    brand: "Altra",
    model: "Escalante 4",
    category: "speed_training",
    weight: 8.5,
    heelStackHeight: 24,
    forefootStackHeight: 24,
    heelToToeDrop: 0,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 140,
    bestFor: ["tempo", "speed_work", "easy_runs"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 3.5,
    responsivenessRating: 4.0,
    comfortRating: 4.2,
    releaseYear: 2024,
    description: "Light zero-drop trainer for natural running and faster workouts."
  },
  {
    brand: "Altra",
    model: "Vanish Carbon 2",
    category: "racing",
    weight: 6.4,
    heelStackHeight: 38,
    forefootStackHeight: 38,
    heelToToeDrop: 0,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 260,
    bestFor: ["racing"],
    minRunnerWeight: 100,
    maxRunnerWeight: 170,
    durabilityRating: 2.0,
    responsivenessRating: 4.8,
    comfortRating: 3.5,
    releaseYear: 2024,
    description: "Zero-drop carbon racer with Altra EGO MAX foam. Unique in the market."
  },
  {
    brand: "Altra",
    model: "Rivera 4",
    category: "daily_trainer",
    weight: 8.8,
    heelStackHeight: 28,
    forefootStackHeight: 28,
    heelToToeDrop: 0,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 130,
    bestFor: ["easy_runs", "tempo"],
    minRunnerWeight: 120,
    maxRunnerWeight: 190,
    durabilityRating: 3.8,
    responsivenessRating: 3.8,
    comfortRating: 4.0,
    releaseYear: 2024,
    description: "Lightweight zero-drop daily trainer with InnerFlex midsole technology."
  },
  {
    brand: "Altra",
    model: "Paradigm 7",
    category: "recovery",
    weight: 10.6,
    heelStackHeight: 32,
    forefootStackHeight: 32,
    heelToToeDrop: 0,
    cushioningLevel: "soft",
    stability: "mild_stability",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 170,
    bestFor: ["easy_runs", "recovery", "long_runs"],
    minRunnerWeight: 150,
    maxRunnerWeight: 240,
    durabilityRating: 4.0,
    responsivenessRating: 3.0,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "Maximum cushion zero-drop trainer with GuideRail support for light stability."
  },
  // ADIDAS
  {
    brand: "Adidas",
    model: "Adizero Adios Pro 3",
    category: "racing",
    weight: 7.8,
    heelStackHeight: 39.5,
    forefootStackHeight: 31.5,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing"],
    minRunnerWeight: 100,
    maxRunnerWeight: 175,
    durabilityRating: 2.3,
    responsivenessRating: 4.9,
    comfortRating: 3.5,
    releaseYear: 2023,
    description: "Elite marathon racer with Lightstrike Pro foam and EnergyRods carbon system."
  },
  {
    brand: "Adidas",
    model: "Adizero Boston 12",
    category: "speed_training",
    weight: 8.5,
    heelStackHeight: 38,
    forefootStackHeight: 30,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 160,
    bestFor: ["tempo", "speed_work", "racing"],
    minRunnerWeight: 120,
    maxRunnerWeight: 190,
    durabilityRating: 3.5,
    responsivenessRating: 4.4,
    comfortRating: 3.8,
    releaseYear: 2024,
    description: "Premium tempo trainer with Lightstrike Pro foam and glass fiber EnergyRods."
  },
  {
    brand: "Adidas",
    model: "Ultraboost Light",
    category: "daily_trainer",
    weight: 10.6,
    heelStackHeight: 32,
    forefootStackHeight: 22,
    heelToToeDrop: 10,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 190,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 230,
    durabilityRating: 4.0,
    responsivenessRating: 3.5,
    comfortRating: 4.8,
    releaseYear: 2023,
    description: "Premium lifestyle/running shoe with Light Boost foam for all-day comfort."
  },
  {
    brand: "Adidas",
    model: "Supernova Rise 2",
    category: "daily_trainer",
    weight: 11.0,
    heelStackHeight: 38,
    forefootStackHeight: 28,
    heelToToeDrop: 10,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 140,
    bestFor: ["easy_runs", "long_runs", "recovery"],
    minRunnerWeight: 150,
    maxRunnerWeight: 250,
    durabilityRating: 4.2,
    responsivenessRating: 3.2,
    comfortRating: 4.6,
    releaseYear: 2024,
    description: "High cushion daily trainer with Dreamstrike+ foam for comfortable, forgiving rides."
  },
  {
    brand: "Adidas",
    model: "Adistar CS 2",
    category: "daily_trainer",
    weight: 11.5,
    heelStackHeight: 40,
    forefootStackHeight: 30,
    heelToToeDrop: 10,
    cushioningLevel: "soft",
    stability: "mild_stability",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 160,
    bestFor: ["easy_runs", "recovery"],
    minRunnerWeight: 160,
    maxRunnerWeight: 260,
    durabilityRating: 4.5,
    responsivenessRating: 2.8,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "Max cushion stability shoe with guidance system for overpronation support."
  },
  // PUMA
  {
    brand: "Puma",
    model: "Deviate Nitro 3",
    category: "speed_training",
    weight: 8.5,
    heelStackHeight: 37,
    forefootStackHeight: 29,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 190,
    bestFor: ["tempo", "speed_work", "racing"],
    minRunnerWeight: 120,
    maxRunnerWeight: 190,
    durabilityRating: 3.5,
    responsivenessRating: 4.3,
    comfortRating: 4.0,
    releaseYear: 2024,
    description: "Carbon-plated training shoe with NITRO Elite foam for fast workouts and racing."
  },
  {
    brand: "Puma",
    model: "Velocity Nitro 3",
    category: "daily_trainer",
    weight: 9.7,
    heelStackHeight: 34,
    forefootStackHeight: 24,
    heelToToeDrop: 10,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 140,
    bestFor: ["easy_runs", "long_runs", "tempo"],
    minRunnerWeight: 130,
    maxRunnerWeight: 210,
    durabilityRating: 4.2,
    responsivenessRating: 3.8,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Versatile daily trainer with NITRO foam for responsive, cushioned miles."
  },
  {
    brand: "Puma",
    model: "Fast-R 2 Nitro Elite",
    category: "racing",
    weight: 6.9,
    heelStackHeight: 39.5,
    forefootStackHeight: 31.5,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 175,
    durabilityRating: 2.3,
    responsivenessRating: 4.9,
    comfortRating: 3.5,
    releaseYear: 2024,
    description: "Elite carbon race shoe with NITRO Elite foam and PWRPLATE for maximum speed."
  },
  {
    brand: "Puma",
    model: "Magnify Nitro 2",
    category: "recovery",
    weight: 11.8,
    heelStackHeight: 40,
    forefootStackHeight: 30,
    heelToToeDrop: 10,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 160,
    bestFor: ["easy_runs", "recovery", "long_runs"],
    minRunnerWeight: 160,
    maxRunnerWeight: 260,
    durabilityRating: 4.0,
    responsivenessRating: 3.0,
    comfortRating: 4.7,
    releaseYear: 2024,
    description: "Maximum cushioned trainer with dual NITRO foam layers for plush, easy runs."
  },
  // MIZUNO
  {
    brand: "Mizuno",
    model: "Wave Rider 28",
    category: "daily_trainer",
    weight: 9.9,
    heelStackHeight: 34,
    forefootStackHeight: 22,
    heelToToeDrop: 12,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 140,
    bestFor: ["easy_runs", "long_runs", "tempo"],
    minRunnerWeight: 130,
    maxRunnerWeight: 220,
    durabilityRating: 4.5,
    responsivenessRating: 3.8,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Classic daily trainer with Wave Plate technology and Enerzy Lite foam."
  },
  {
    brand: "Mizuno",
    model: "Wave Sky 7",
    category: "long_run",
    weight: 11.2,
    heelStackHeight: 38,
    forefootStackHeight: 26,
    heelToToeDrop: 12,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 165,
    bestFor: ["long_runs", "easy_runs", "recovery"],
    minRunnerWeight: 160,
    maxRunnerWeight: 260,
    durabilityRating: 4.3,
    responsivenessRating: 3.0,
    comfortRating: 4.7,
    releaseYear: 2023,
    description: "Max cushion daily trainer with Enerzy Core foam and Wave Plate for smooth rides."
  },
  {
    brand: "Mizuno",
    model: "Wave Rebellion Pro 2",
    category: "racing",
    weight: 7.4,
    heelStackHeight: 39.5,
    forefootStackHeight: 31.5,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 275,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 175,
    durabilityRating: 2.5,
    responsivenessRating: 4.8,
    comfortRating: 3.6,
    releaseYear: 2024,
    description: "Elite carbon race shoe with Enerzy Lite Plus foam and carbon-infused Wave Plate."
  },
  {
    brand: "Mizuno",
    model: "Wave Inspire 20",
    category: "daily_trainer",
    weight: 10.4,
    heelStackHeight: 36,
    forefootStackHeight: 24,
    heelToToeDrop: 12,
    cushioningLevel: "medium",
    stability: "mild_stability",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 145,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 240,
    durabilityRating: 4.5,
    responsivenessRating: 3.5,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Stability trainer with Mizuno Wave plate and fan-shaped Wave tech for support."
  },
  // TRAIL RUNNING SHOES
  {
    brand: "Nike",
    model: "Wildhorse 8",
    category: "trail",
    weight: 9.2,
    heelStackHeight: 35.5,
    forefootStackHeight: 27.5,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 130,
    bestFor: ["trail_running"],
    minRunnerWeight: 130,
    maxRunnerWeight: 210,
    durabilityRating: 4.0,
    responsivenessRating: 3.5,
    comfortRating: 4.3,
    releaseYear: 2023,
    description: "Max cushion trail shoe with React foam and integrated rock plate."
  },
  {
    brand: "Nike",
    model: "Zegama 2",
    category: "trail",
    weight: 10.5,
    heelStackHeight: 37,
    forefootStackHeight: 29,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 160,
    bestFor: ["trail_running", "speed_work"],
    minRunnerWeight: 120,
    maxRunnerWeight: 200,
    durabilityRating: 3.8,
    responsivenessRating: 4.2,
    comfortRating: 4.0,
    releaseYear: 2024,
    description: "Technical trail racer with ZoomX foam for fast mountain running."
  },
  {
    brand: "Hoka",
    model: "Speedgoat 6",
    category: "trail",
    weight: 10.0,
    heelStackHeight: 40,
    forefootStackHeight: 35,
    heelToToeDrop: 5,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 155,
    bestFor: ["trail_running", "long_runs"],
    minRunnerWeight: 130,
    maxRunnerWeight: 220,
    durabilityRating: 4.2,
    responsivenessRating: 3.8,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "Iconic trail shoe with Vibram Megagrip outsole and max cushion for ultras."
  },
  {
    brand: "Hoka",
    model: "Tecton X 2",
    category: "trail",
    weight: 8.5,
    heelStackHeight: 38,
    forefootStackHeight: 33,
    heelToToeDrop: 5,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 225,
    bestFor: ["trail_running", "racing"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 3.0,
    responsivenessRating: 4.5,
    comfortRating: 3.8,
    releaseYear: 2024,
    description: "Carbon-plated trail racer with PEBA foam for fast, technical terrain."
  },
  {
    brand: "Hoka",
    model: "Torrent 3",
    category: "trail",
    weight: 8.6,
    heelStackHeight: 29,
    forefootStackHeight: 24,
    heelToToeDrop: 5,
    cushioningLevel: "firm",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 140,
    bestFor: ["trail_running", "speed_work"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 3.5,
    responsivenessRating: 4.2,
    comfortRating: 3.8,
    releaseYear: 2024,
    description: "Light, nimble trail shoe for fast efforts on non-technical terrain."
  },
  {
    brand: "Brooks",
    model: "Cascadia 18",
    category: "trail",
    weight: 10.6,
    heelStackHeight: 34,
    forefootStackHeight: 26,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 140,
    bestFor: ["trail_running", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 230,
    durabilityRating: 4.3,
    responsivenessRating: 3.5,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Rugged trail workhorse with TrailTack rubber and DNA LOFT cushioning."
  },
  {
    brand: "Brooks",
    model: "Caldera 7",
    category: "trail",
    weight: 11.2,
    heelStackHeight: 38,
    forefootStackHeight: 30,
    heelToToeDrop: 8,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 170,
    bestFor: ["trail_running", "long_runs"],
    minRunnerWeight: 150,
    maxRunnerWeight: 250,
    durabilityRating: 4.0,
    responsivenessRating: 3.2,
    comfortRating: 4.6,
    releaseYear: 2024,
    description: "Max cushion trail shoe with DNA LOFT v2 foam for ultra distances."
  },
  {
    brand: "Asics",
    model: "Trabuco Max 3",
    category: "trail",
    weight: 11.5,
    heelStackHeight: 37,
    forefootStackHeight: 32,
    heelToToeDrop: 5,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 170,
    bestFor: ["trail_running", "long_runs"],
    minRunnerWeight: 150,
    maxRunnerWeight: 250,
    durabilityRating: 4.0,
    responsivenessRating: 3.3,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "Max cushion trail shoe with FF BLAST PLUS foam for ultra distances."
  },
  {
    brand: "Asics",
    model: "Fujilite 4",
    category: "trail",
    weight: 8.8,
    heelStackHeight: 29,
    forefootStackHeight: 21,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 130,
    bestFor: ["trail_running", "speed_work"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 3.5,
    responsivenessRating: 4.0,
    comfortRating: 3.8,
    releaseYear: 2024,
    description: "Lightweight trail shoe for fast efforts on moderate terrain."
  },
  {
    brand: "Saucony",
    model: "Peregrine 14",
    category: "trail",
    weight: 9.7,
    heelStackHeight: 30,
    forefootStackHeight: 26,
    heelToToeDrop: 4,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 140,
    bestFor: ["trail_running"],
    minRunnerWeight: 120,
    maxRunnerWeight: 200,
    durabilityRating: 4.0,
    responsivenessRating: 3.8,
    comfortRating: 4.2,
    releaseYear: 2024,
    description: "Versatile trail shoe with PWRRUN foam and rock plate protection."
  },
  {
    brand: "Saucony",
    model: "Xodus Ultra 2",
    category: "trail",
    weight: 11.8,
    heelStackHeight: 37,
    forefootStackHeight: 33,
    heelToToeDrop: 4,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 180,
    bestFor: ["trail_running", "long_runs"],
    minRunnerWeight: 150,
    maxRunnerWeight: 250,
    durabilityRating: 4.2,
    responsivenessRating: 3.2,
    comfortRating: 4.6,
    releaseYear: 2024,
    description: "Max cushion trail shoe with PWRRUN PB foam for ultra distances."
  },
  {
    brand: "Salomon",
    model: "Speedcross 6",
    category: "trail",
    weight: 10.5,
    heelStackHeight: 32,
    forefootStackHeight: 22,
    heelToToeDrop: 10,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 145,
    bestFor: ["trail_running"],
    minRunnerWeight: 130,
    maxRunnerWeight: 210,
    durabilityRating: 4.0,
    responsivenessRating: 3.5,
    comfortRating: 4.0,
    releaseYear: 2023,
    description: "Aggressive trail shoe with deep lugs for muddy and technical terrain."
  },
  {
    brand: "Salomon",
    model: "Ultra Glide 2",
    category: "trail",
    weight: 10.2,
    heelStackHeight: 35,
    forefootStackHeight: 27,
    heelToToeDrop: 8,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 160,
    bestFor: ["trail_running", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 230,
    durabilityRating: 4.0,
    responsivenessRating: 3.5,
    comfortRating: 4.5,
    releaseYear: 2023,
    description: "Cushioned ultra trail shoe with rocker geometry for long distances."
  },
  {
    brand: "Salomon",
    model: "S/Lab Ultra 3",
    category: "trail",
    weight: 9.0,
    heelStackHeight: 32,
    forefootStackHeight: 24,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 200,
    bestFor: ["trail_running", "racing"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 3.5,
    responsivenessRating: 4.2,
    comfortRating: 4.0,
    releaseYear: 2024,
    description: "Premium ultra trail racing shoe with energy foam for elite performance."
  },
  {
    brand: "Salomon",
    model: "Sense Ride 5",
    category: "trail",
    weight: 9.8,
    heelStackHeight: 31,
    forefootStackHeight: 23,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 140,
    bestFor: ["trail_running", "tempo"],
    minRunnerWeight: 120,
    maxRunnerWeight: 200,
    durabilityRating: 4.0,
    responsivenessRating: 4.0,
    comfortRating: 4.2,
    releaseYear: 2023,
    description: "Versatile trail shoe that handles road-to-trail transitions smoothly."
  },
  {
    brand: "New Balance",
    model: "Fresh Foam X Hierro v8",
    category: "trail",
    weight: 11.0,
    heelStackHeight: 36,
    forefootStackHeight: 28,
    heelToToeDrop: 8,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 150,
    bestFor: ["trail_running", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 230,
    durabilityRating: 4.2,
    responsivenessRating: 3.3,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "Max cushion trail shoe with Fresh Foam X and Vibram Megagrip outsole."
  },
  {
    brand: "La Sportiva",
    model: "Prodigio",
    category: "trail",
    weight: 10.8,
    heelStackHeight: 38,
    forefootStackHeight: 32,
    heelToToeDrop: 6,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["trail_running", "racing"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 3.2,
    responsivenessRating: 4.5,
    comfortRating: 3.8,
    releaseYear: 2024,
    description: "Carbon-plated trail racing shoe with EVA cushioning for fast ultras."
  },
  {
    brand: "La Sportiva",
    model: "Jackal II",
    category: "trail",
    weight: 10.2,
    heelStackHeight: 35,
    forefootStackHeight: 29,
    heelToToeDrop: 6,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 175,
    bestFor: ["trail_running", "long_runs"],
    minRunnerWeight: 130,
    maxRunnerWeight: 210,
    durabilityRating: 4.3,
    responsivenessRating: 3.8,
    comfortRating: 4.2,
    releaseYear: 2023,
    description: "Technical mountain shoe with FriXion outsole for rugged terrain."
  },
  {
    brand: "Altra",
    model: "Olympus 6",
    category: "trail",
    weight: 11.5,
    heelStackHeight: 36,
    forefootStackHeight: 36,
    heelToToeDrop: 0,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 170,
    bestFor: ["trail_running", "long_runs"],
    minRunnerWeight: 150,
    maxRunnerWeight: 250,
    durabilityRating: 4.0,
    responsivenessRating: 3.0,
    comfortRating: 4.6,
    releaseYear: 2024,
    description: "Max cushion zero-drop trail shoe for ultra distances and recovery."
  },
  {
    brand: "Altra",
    model: "Lone Peak 8",
    category: "trail",
    weight: 10.2,
    heelStackHeight: 28,
    forefootStackHeight: 28,
    heelToToeDrop: 0,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 150,
    bestFor: ["trail_running"],
    minRunnerWeight: 130,
    maxRunnerWeight: 210,
    durabilityRating: 4.2,
    responsivenessRating: 3.5,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Iconic zero-drop trail shoe with wide toe box and balanced cushioning."
  },
  // OLDER MODEL VERSIONS (Previous Year)
  {
    brand: "Nike",
    model: "Pegasus 40",
    category: "daily_trainer",
    weight: 9.9,
    heelStackHeight: 33,
    forefootStackHeight: 23,
    heelToToeDrop: 10,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 130,
    bestFor: ["easy_runs", "long_runs", "tempo"],
    minRunnerWeight: 120,
    maxRunnerWeight: 220,
    durabilityRating: 4.2,
    responsivenessRating: 3.6,
    comfortRating: 4.4,
    releaseYear: 2023,
    description: "Previous generation Pegasus with React foam. Great value workhorse trainer."
  },
  {
    brand: "Brooks",
    model: "Ghost 15",
    category: "daily_trainer",
    weight: 9.8,
    heelStackHeight: 35,
    forefootStackHeight: 23,
    heelToToeDrop: 12,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 130,
    bestFor: ["easy_runs", "long_runs", "tempo"],
    minRunnerWeight: 130,
    maxRunnerWeight: 220,
    durabilityRating: 4.5,
    responsivenessRating: 3.4,
    comfortRating: 4.4,
    releaseYear: 2023,
    description: "Previous generation Ghost with DNA LOFT v2. Reliable daily trainer."
  },
  {
    brand: "Hoka",
    model: "Clifton 8",
    category: "daily_trainer",
    weight: 9.0,
    heelStackHeight: 29,
    forefootStackHeight: 24,
    heelToToeDrop: 5,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 135,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 120,
    maxRunnerWeight: 200,
    durabilityRating: 3.7,
    responsivenessRating: 3.4,
    comfortRating: 4.7,
    releaseYear: 2022,
    description: "Previous generation Clifton with EVA cushioning. Budget-friendly plush ride."
  },
  {
    brand: "Nike",
    model: "Pegasus 39",
    category: "daily_trainer",
    weight: 9.8,
    heelStackHeight: 33,
    forefootStackHeight: 23,
    heelToToeDrop: 10,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 130,
    bestFor: ["easy_runs", "long_runs", "tempo"],
    minRunnerWeight: 120,
    maxRunnerWeight: 220,
    durabilityRating: 4.2,
    responsivenessRating: 3.5,
    comfortRating: 4.3,
    releaseYear: 2022,
    description: "Classic Pegasus with React foam and forefoot Air Zoom unit. Reliable training workhorse."
  },
  {
    brand: "Brooks",
    model: "Ghost 14",
    category: "daily_trainer",
    weight: 10.1,
    heelStackHeight: 36,
    forefootStackHeight: 24,
    heelToToeDrop: 12,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 140,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 130,
    maxRunnerWeight: 220,
    durabilityRating: 4.5,
    responsivenessRating: 3.3,
    comfortRating: 4.4,
    releaseYear: 2021,
    description: "Brooks first carbon-neutral shoe with 100% DNA LOFT cushioning. Smooth transitions."
  },
  {
    brand: "Hoka",
    model: "Clifton 7",
    category: "daily_trainer",
    weight: 8.7,
    heelStackHeight: 29,
    forefootStackHeight: 24,
    heelToToeDrop: 5,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 130,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 120,
    maxRunnerWeight: 200,
    durabilityRating: 3.5,
    responsivenessRating: 3.3,
    comfortRating: 4.6,
    releaseYear: 2020,
    description: "Lightweight Clifton with full-compression EVA foam and early-stage Meta-Rocker."
  },
  // SAUCONY ENDORPHIN PRO SERIES
  {
    brand: "Saucony",
    model: "Endorphin Pro 4",
    category: "racing",
    weight: 7.7,
    heelStackHeight: 40,
    forefootStackHeight: 32,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 225,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 180,
    durabilityRating: 3.0,
    responsivenessRating: 4.8,
    comfortRating: 4.2,
    releaseYear: 2024,
    description: "Dual-foam super shoe with PWRRUN HG top layer and PWRRUN PB base. Most stable Endorphin Pro yet."
  },
  {
    brand: "Saucony",
    model: "Endorphin Pro 3",
    category: "racing",
    weight: 7.2,
    heelStackHeight: 39.5,
    forefootStackHeight: 31.5,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 225,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 175,
    durabilityRating: 2.8,
    responsivenessRating: 4.9,
    comfortRating: 4.0,
    releaseYear: 2022,
    description: "Bouncy carbon-plated racer with PWRRUN PB foam. Major stack increase for marathon comfort."
  },
  {
    brand: "Saucony",
    model: "Endorphin Pro 2",
    category: "racing",
    weight: 7.0,
    heelStackHeight: 35.5,
    forefootStackHeight: 27.5,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 200,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 170,
    durabilityRating: 2.5,
    responsivenessRating: 4.8,
    comfortRating: 3.8,
    releaseYear: 2021,
    description: "Second generation with refined PWRRUN PB foam and improved fit. Fast and snappy."
  },
  // ADIDAS ADIOS PRO SERIES
  {
    brand: "Adidas",
    model: "Adizero Adios Pro 3",
    category: "racing",
    weight: 7.6,
    heelStackHeight: 39.5,
    forefootStackHeight: 33,
    heelToToeDrop: 6.5,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing"],
    minRunnerWeight: 100,
    maxRunnerWeight: 180,
    durabilityRating: 3.2,
    responsivenessRating: 4.9,
    comfortRating: 4.0,
    releaseYear: 2022,
    description: "Boston Marathon dominator with dual Lightstrike Pro foam layers and Energy Rods 2.0 carbon system."
  },
  {
    brand: "Adidas",
    model: "Adizero Adios Pro 2",
    category: "racing",
    weight: 8.0,
    heelStackHeight: 39,
    forefootStackHeight: 32.5,
    heelToToeDrop: 6.5,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 220,
    bestFor: ["racing"],
    minRunnerWeight: 100,
    maxRunnerWeight: 180,
    durabilityRating: 3.0,
    responsivenessRating: 4.8,
    comfortRating: 3.8,
    releaseYear: 2021,
    description: "Carbon-rod super shoe with Lightstrike Pro foam. Known for setting world records."
  },
  // ASICS METASPEED SERIES
  {
    brand: "Asics",
    model: "Metaspeed Sky Paris",
    category: "racing",
    weight: 6.4,
    heelStackHeight: 39.5,
    forefootStackHeight: 34.5,
    heelToToeDrop: 5,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing"],
    minRunnerWeight: 100,
    maxRunnerWeight: 170,
    durabilityRating: 2.5,
    responsivenessRating: 5.0,
    comfortRating: 4.0,
    releaseYear: 2024,
    description: "Lightest super shoe on the market with upgraded FF Turbo+ foam. 73% heel energy return."
  },
  {
    brand: "Asics",
    model: "Metaspeed Sky+",
    category: "racing",
    weight: 7.2,
    heelStackHeight: 39,
    forefootStackHeight: 34,
    heelToToeDrop: 5,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing"],
    minRunnerWeight: 100,
    maxRunnerWeight: 175,
    durabilityRating: 2.8,
    responsivenessRating: 4.9,
    comfortRating: 3.9,
    releaseYear: 2022,
    description: "For stride-style runners with FF Turbo foam and flatter carbon plate. Increased foam volume."
  },
  {
    brand: "Asics",
    model: "Metaspeed Edge Paris",
    category: "racing",
    weight: 6.5,
    heelStackHeight: 39.5,
    forefootStackHeight: 34.5,
    heelToToeDrop: 5,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 170,
    durabilityRating: 2.5,
    responsivenessRating: 5.0,
    comfortRating: 4.0,
    releaseYear: 2024,
    description: "For cadence-style runners with upgraded FF Turbo+ foam and curved carbon plate."
  },
  {
    brand: "Asics",
    model: "Metaspeed Edge+",
    category: "racing",
    weight: 7.4,
    heelStackHeight: 39,
    forefootStackHeight: 31,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 175,
    durabilityRating: 2.8,
    responsivenessRating: 4.8,
    comfortRating: 3.8,
    releaseYear: 2022,
    description: "Cadence-focused racer with FF Blast Turbo foam and curved carbon plate for quick turnover."
  },
  {
    brand: "Asics",
    model: "Gel-Nimbus 25",
    category: "long_run",
    weight: 10.2,
    heelStackHeight: 39.5,
    forefootStackHeight: 31.5,
    heelToToeDrop: 8,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 150,
    bestFor: ["long_runs", "easy_runs", "recovery"],
    minRunnerWeight: 150,
    maxRunnerWeight: 250,
    durabilityRating: 4.1,
    responsivenessRating: 3.3,
    comfortRating: 4.7,
    releaseYear: 2023,
    description: "Previous generation Nimbus with FF BLAST PLUS foam. Excellent value."
  },
  {
    brand: "Saucony",
    model: "Ride 16",
    category: "daily_trainer",
    weight: 9.2,
    heelStackHeight: 33,
    forefootStackHeight: 25,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 130,
    bestFor: ["easy_runs", "long_runs", "tempo"],
    minRunnerWeight: 130,
    maxRunnerWeight: 210,
    durabilityRating: 4.1,
    responsivenessRating: 3.7,
    comfortRating: 4.4,
    releaseYear: 2023,
    description: "Previous generation Ride with PWRRUN+ foam. Great value daily trainer."
  },
  {
    brand: "New Balance",
    model: "Fresh Foam X 1080v13",
    category: "daily_trainer",
    weight: 9.5,
    heelStackHeight: 36,
    forefootStackHeight: 30,
    heelToToeDrop: 6,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 155,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 230,
    durabilityRating: 3.9,
    responsivenessRating: 3.6,
    comfortRating: 4.7,
    releaseYear: 2023,
    description: "Previous generation 1080 with Fresh Foam X midsole. Excellent cushioning."
  },
  {
    brand: "On",
    model: "Cloudmonster",
    category: "daily_trainer",
    weight: 9.7,
    heelStackHeight: 29,
    forefootStackHeight: 21,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 160,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 220,
    durabilityRating: 3.8,
    responsivenessRating: 4.0,
    comfortRating: 4.2,
    releaseYear: 2022,
    description: "Original Cloudmonster with CloudTec and Helion foam. More versatile than v2."
  },
  {
    brand: "Adidas",
    model: "Adizero SL 2",
    category: "speed_training",
    weight: 7.8,
    heelStackHeight: 32,
    forefootStackHeight: 24,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 130,
    bestFor: ["tempo", "speed_work", "easy_runs"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 3.8,
    responsivenessRating: 4.3,
    comfortRating: 4.0,
    releaseYear: 2024,
    description: "Lightweight tempo trainer with Lightstrike Pro foam. Great value speed shoe."
  },
  {
    brand: "Adidas",
    model: "Takumi Sen 10",
    category: "racing",
    weight: 6.8,
    heelStackHeight: 33,
    forefootStackHeight: 25,
    heelToToeDrop: 8,
    cushioningLevel: "firm",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 200,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 160,
    durabilityRating: 2.5,
    responsivenessRating: 4.8,
    comfortRating: 3.5,
    releaseYear: 2024,
    description: "Lightweight carbon racer for 5K to half marathon. Aggressive rocker geometry."
  },
  {
    brand: "Puma",
    model: "Liberate Nitro 3",
    category: "speed_training",
    weight: 7.3,
    heelStackHeight: 28,
    forefootStackHeight: 20,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 120,
    bestFor: ["tempo", "speed_work", "racing"],
    minRunnerWeight: 100,
    maxRunnerWeight: 170,
    durabilityRating: 3.5,
    responsivenessRating: 4.3,
    comfortRating: 3.8,
    releaseYear: 2024,
    description: "Lightweight uptempo shoe with NITRO foam. Great value for speed training."
  },
  {
    brand: "Mizuno",
    model: "Wave Rebellion Flash 2",
    category: "speed_training",
    weight: 7.8,
    heelStackHeight: 35,
    forefootStackHeight: 27,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 145,
    bestFor: ["tempo", "speed_work", "racing"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 3.5,
    responsivenessRating: 4.4,
    comfortRating: 3.9,
    releaseYear: 2024,
    description: "Nylon plate tempo trainer with Enerzy Lite foam for fast training."
  },
  {
    brand: "Reebok",
    model: "Floatride Energy 5",
    category: "daily_trainer",
    weight: 9.0,
    heelStackHeight: 30,
    forefootStackHeight: 22,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 100,
    bestFor: ["easy_runs", "long_runs", "tempo"],
    minRunnerWeight: 120,
    maxRunnerWeight: 200,
    durabilityRating: 4.2,
    responsivenessRating: 4.0,
    comfortRating: 4.2,
    releaseYear: 2024,
    description: "Value daily trainer with Floatride Energy foam. Excellent bang for buck."
  },
  {
    brand: "Reebok",
    model: "Floatride Energy X",
    category: "racing",
    weight: 7.2,
    heelStackHeight: 39,
    forefootStackHeight: 31,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 180,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 175,
    durabilityRating: 2.8,
    responsivenessRating: 4.6,
    comfortRating: 3.6,
    releaseYear: 2023,
    description: "Carbon-plated racer with Floatride Energy foam. Affordable super shoe."
  },
  {
    brand: "Under Armour",
    model: "Velociti Elite",
    category: "racing",
    weight: 6.8,
    heelStackHeight: 38,
    forefootStackHeight: 30,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 170,
    durabilityRating: 2.5,
    responsivenessRating: 4.8,
    comfortRating: 3.5,
    releaseYear: 2024,
    description: "Elite carbon racer with PEBA-based Propulsion Foam. Super shoe performance."
  },
  {
    brand: "Under Armour",
    model: "Infinite Elite",
    category: "daily_trainer",
    weight: 9.5,
    heelStackHeight: 35,
    forefootStackHeight: 27,
    heelToToeDrop: 8,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 160,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 230,
    durabilityRating: 4.0,
    responsivenessRating: 3.5,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "Premium cushioned trainer with UA Flow foam for smooth, comfortable miles."
  },
  {
    brand: "361°",
    model: "Flame QL",
    category: "daily_trainer",
    weight: 8.8,
    heelStackHeight: 33,
    forefootStackHeight: 25,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 150,
    bestFor: ["easy_runs", "long_runs", "tempo"],
    minRunnerWeight: 120,
    maxRunnerWeight: 200,
    durabilityRating: 4.0,
    responsivenessRating: 4.2,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Versatile trainer with QU!KFOAM and QU!KFLAME tech. Great value performance."
  },
  {
    brand: "361°",
    model: "Feisu 4 Pro",
    category: "racing",
    weight: 6.7,
    heelStackHeight: 39,
    forefootStackHeight: 31,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 220,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 170,
    durabilityRating: 2.5,
    responsivenessRating: 4.9,
    comfortRating: 3.5,
    releaseYear: 2024,
    description: "Elite carbon racer used by world record holders. Premium PEBA foam."
  },
  {
    brand: "Nike",
    model: "Streakfly",
    category: "racing",
    weight: 5.6,
    heelStackHeight: 28,
    forefootStackHeight: 22,
    heelToToeDrop: 6,
    cushioningLevel: "firm",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 170,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 90,
    maxRunnerWeight: 155,
    durabilityRating: 2.5,
    responsivenessRating: 4.6,
    comfortRating: 3.3,
    releaseYear: 2023,
    description: "Lightweight 5K-10K racer with ZoomX foam. No carbon plate, pure speed."
  },
  {
    brand: "Asics",
    model: "Metaspeed Edge Paris",
    category: "racing",
    weight: 6.9,
    heelStackHeight: 35,
    forefootStackHeight: 30,
    heelToToeDrop: 5,
    cushioningLevel: "firm",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 165,
    durabilityRating: 2.0,
    responsivenessRating: 5.0,
    comfortRating: 3.4,
    releaseYear: 2024,
    description: "Elite carbon racer optimized for cadence runners. FF TURBO PLUS foam."
  },
  {
    brand: "Brooks",
    model: "Hyperion Max 2",
    category: "speed_training",
    weight: 7.8,
    heelStackHeight: 36,
    forefootStackHeight: 28,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 180,
    bestFor: ["tempo", "speed_work", "racing"],
    minRunnerWeight: 115,
    maxRunnerWeight: 185,
    durabilityRating: 3.5,
    responsivenessRating: 4.4,
    comfortRating: 4.0,
    releaseYear: 2024,
    description: "Light, fast tempo trainer with DNA FLASH midsole for uptempo workouts."
  },
  {
    brand: "Hoka",
    model: "Cielo X1",
    category: "racing",
    weight: 6.3,
    heelStackHeight: 37,
    forefootStackHeight: 32,
    heelToToeDrop: 5,
    cushioningLevel: "firm",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 275,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 95,
    maxRunnerWeight: 160,
    durabilityRating: 2.0,
    responsivenessRating: 5.0,
    comfortRating: 3.3,
    releaseYear: 2024,
    description: "Ultralight carbon racer with PEBA foam. Hoka's fastest racing shoe."
  },
  {
    brand: "New Balance",
    model: "SC Elite v4",
    category: "racing",
    weight: 6.5,
    heelStackHeight: 39,
    forefootStackHeight: 31,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 230,
    bestFor: ["racing"],
    minRunnerWeight: 100,
    maxRunnerWeight: 170,
    durabilityRating: 2.3,
    responsivenessRating: 4.9,
    comfortRating: 3.5,
    releaseYear: 2024,
    description: "Elite carbon racer with FuelCell foam and carbon fiber plate."
  },
  {
    brand: "Saucony",
    model: "Triumph 21",
    category: "long_run",
    weight: 10.0,
    heelStackHeight: 36,
    forefootStackHeight: 26,
    heelToToeDrop: 10,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 150,
    bestFor: ["long_runs", "easy_runs", "recovery"],
    minRunnerWeight: 150,
    maxRunnerWeight: 240,
    durabilityRating: 3.9,
    responsivenessRating: 3.4,
    comfortRating: 4.7,
    releaseYear: 2023,
    description: "Previous generation Triumph with PWRRUN PB foam. Great value max cushion."
  }
];

