import type { InsertRunningShoe } from "@shared/schema";

export const shoeData: InsertRunningShoe[] = [
  // NIKE
  {
    brand: "Nike",
    model: "Pegasus 41",
    category: "daily_trainer",
    weight: 10.2,
    heelStackHeight: 33,
    forefootStackHeight: 23,
    heelToToeDrop: 10,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 140,
    bestFor: ["easy_runs", "long_runs", "tempo"],
    minRunnerWeight: 120,
    maxRunnerWeight: 220,
    durabilityRating: 4.2,
    responsivenessRating: 3.8,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "The workhorse daily trainer with React X foam. Versatile for all training types."
  },
  {
    brand: "Nike",
    model: "Vaporfly 3",
    category: "racing",
    weight: 6.6,
    heelStackHeight: 40,
    forefootStackHeight: 32,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 260,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 180,
    durabilityRating: 2.5,
    responsivenessRating: 5.0,
    comfortRating: 3.8,
    releaseYear: 2023,
    description: "Elite marathon racing shoe with ZoomX foam and carbon plate. Maximum energy return."
  },
  {
    brand: "Nike",
    model: "Alphafly 3",
    category: "racing",
    weight: 7.4,
    heelStackHeight: 40,
    forefootStackHeight: 36,
    heelToToeDrop: 4,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 285,
    bestFor: ["racing"],
    minRunnerWeight: 100,
    maxRunnerWeight: 170,
    durabilityRating: 2.0,
    responsivenessRating: 5.0,
    comfortRating: 3.5,
    releaseYear: 2024,
    description: "The ultimate marathon super shoe with Air Zoom pods and full-length carbon plate."
  },
  {
    brand: "Nike",
    model: "Invincible 3",
    category: "recovery",
    weight: 10.6,
    heelStackHeight: 37,
    forefootStackHeight: 28,
    heelToToeDrop: 9,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 180,
    bestFor: ["easy_runs", "recovery"],
    minRunnerWeight: 140,
    maxRunnerWeight: 250,
    durabilityRating: 3.5,
    responsivenessRating: 3.0,
    comfortRating: 5.0,
    releaseYear: 2023,
    description: "Maximum cushioned recovery shoe with plush ZoomX foam for easy days."
  },
  {
    brand: "Nike",
    model: "Vomero 18",
    category: "daily_trainer",
    weight: 10.9,
    heelStackHeight: 36,
    forefootStackHeight: 26,
    heelToToeDrop: 10,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 160,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 230,
    durabilityRating: 4.0,
    responsivenessRating: 3.5,
    comfortRating: 4.8,
    releaseYear: 2024,
    description: "Premium cushioned daily trainer with ZoomX midsole for comfortable miles."
  },
  // BROOKS
  {
    brand: "Brooks",
    model: "Ghost 16",
    category: "daily_trainer",
    weight: 10.1,
    heelStackHeight: 35,
    forefootStackHeight: 23,
    heelToToeDrop: 12,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 140,
    bestFor: ["easy_runs", "long_runs", "tempo"],
    minRunnerWeight: 130,
    maxRunnerWeight: 220,
    durabilityRating: 4.5,
    responsivenessRating: 3.5,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "Smooth, balanced daily trainer with DNA LOFT v2 cushioning. A true workhorse."
  },
  {
    brand: "Brooks",
    model: "Glycerin 21",
    category: "long_run",
    weight: 10.6,
    heelStackHeight: 38,
    forefootStackHeight: 28,
    heelToToeDrop: 10,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 160,
    bestFor: ["long_runs", "easy_runs", "recovery"],
    minRunnerWeight: 150,
    maxRunnerWeight: 240,
    durabilityRating: 4.2,
    responsivenessRating: 3.2,
    comfortRating: 5.0,
    releaseYear: 2024,
    description: "Max cushion daily trainer with plush GlycerinHD foam. Ideal for long runs."
  },
  {
    brand: "Brooks",
    model: "Hyperion Elite 3",
    category: "racing",
    weight: 7.0,
    heelStackHeight: 39.5,
    forefootStackHeight: 31.5,
    heelToToeDrop: 8,
    cushioningLevel: "firm",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 2.5,
    responsivenessRating: 4.8,
    comfortRating: 3.5,
    releaseYear: 2023,
    description: "Elite carbon racing shoe with DNA FLASH midsole for race day performance."
  },
  {
    brand: "Brooks",
    model: "Adrenaline GTS 24",
    category: "daily_trainer",
    weight: 10.4,
    heelStackHeight: 36,
    forefootStackHeight: 24,
    heelToToeDrop: 12,
    cushioningLevel: "medium",
    stability: "mild_stability",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 140,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 130,
    maxRunnerWeight: 230,
    durabilityRating: 4.5,
    responsivenessRating: 3.3,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Stability trainer with GuideRails holistic support system. Great for overpronators."
  },
  // HOKA
  {
    brand: "Hoka",
    model: "Clifton 9",
    category: "daily_trainer",
    weight: 9.0,
    heelStackHeight: 36,
    forefootStackHeight: 31,
    heelToToeDrop: 5,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 145,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 120,
    maxRunnerWeight: 200,
    durabilityRating: 3.8,
    responsivenessRating: 3.5,
    comfortRating: 4.8,
    releaseYear: 2023,
    description: "Lightweight cushioned trainer with signature Hoka marshmallow feel."
  },
  {
    brand: "Hoka",
    model: "Bondi 8",
    category: "recovery",
    weight: 10.8,
    heelStackHeight: 37,
    forefootStackHeight: 33,
    heelToToeDrop: 4,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 165,
    bestFor: ["easy_runs", "recovery", "long_runs"],
    minRunnerWeight: 150,
    maxRunnerWeight: 260,
    durabilityRating: 4.0,
    responsivenessRating: 2.8,
    comfortRating: 5.0,
    releaseYear: 2023,
    description: "Maximum cushioned shoe for high mileage and recovery runs. Ultra plush."
  },
  {
    brand: "Hoka",
    model: "Mach 6",
    category: "speed_training",
    weight: 7.9,
    heelStackHeight: 35,
    forefootStackHeight: 30,
    heelToToeDrop: 5,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 140,
    bestFor: ["tempo", "speed_work", "racing"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 3.5,
    responsivenessRating: 4.5,
    comfortRating: 4.0,
    releaseYear: 2024,
    description: "Light and fast tempo trainer with PEBA foam. Great for uptempo workouts."
  },
  {
    brand: "Hoka",
    model: "Rocket X 2",
    category: "racing",
    weight: 7.4,
    heelStackHeight: 39,
    forefootStackHeight: 34,
    heelToToeDrop: 5,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 175,
    durabilityRating: 2.5,
    responsivenessRating: 4.8,
    comfortRating: 3.8,
    releaseYear: 2023,
    description: "Carbon-plated race day shoe with PEBA foam for maximum speed."
  },
  {
    brand: "Hoka",
    model: "Arahi 7",
    category: "daily_trainer",
    weight: 9.5,
    heelStackHeight: 35,
    forefootStackHeight: 30,
    heelToToeDrop: 5,
    cushioningLevel: "medium",
    stability: "mild_stability",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 150,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 130,
    maxRunnerWeight: 220,
    durabilityRating: 4.0,
    responsivenessRating: 3.5,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Stability shoe with J-Frame technology for mild overpronation support."
  },
  // ASICS
  {
    brand: "Asics",
    model: "Gel-Nimbus 26",
    category: "long_run",
    weight: 10.4,
    heelStackHeight: 41,
    forefootStackHeight: 33,
    heelToToeDrop: 8,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 160,
    bestFor: ["long_runs", "easy_runs", "recovery"],
    minRunnerWeight: 150,
    maxRunnerWeight: 250,
    durabilityRating: 4.2,
    responsivenessRating: 3.2,
    comfortRating: 4.8,
    releaseYear: 2024,
    description: "Premium neutral cushioned shoe with FF BLAST PLUS ECO foam."
  },
  {
    brand: "Asics",
    model: "Gel-Kayano 31",
    category: "daily_trainer",
    weight: 11.0,
    heelStackHeight: 40,
    forefootStackHeight: 27,
    heelToToeDrop: 13,
    cushioningLevel: "medium",
    stability: "motion_control",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 160,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 160,
    maxRunnerWeight: 260,
    durabilityRating: 4.5,
    responsivenessRating: 3.0,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Premium stability shoe with 4D Guidance System for maximum support."
  },
  {
    brand: "Asics",
    model: "Novablast 4",
    category: "daily_trainer",
    weight: 9.2,
    heelStackHeight: 37,
    forefootStackHeight: 29,
    heelToToeDrop: 8,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 140,
    bestFor: ["easy_runs", "long_runs", "tempo"],
    minRunnerWeight: 120,
    maxRunnerWeight: 200,
    durabilityRating: 3.8,
    responsivenessRating: 4.2,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "Bouncy daily trainer with FF BLAST PLUS foam for energetic rides."
  },
  {
    brand: "Asics",
    model: "Metaspeed Sky Paris",
    category: "racing",
    weight: 6.7,
    heelStackHeight: 39.5,
    forefootStackHeight: 34.5,
    heelToToeDrop: 5,
    cushioningLevel: "firm",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 250,
    bestFor: ["racing"],
    minRunnerWeight: 100,
    maxRunnerWeight: 170,
    durabilityRating: 2.0,
    responsivenessRating: 5.0,
    comfortRating: 3.5,
    releaseYear: 2024,
    description: "Elite marathon racing shoe with FF TURBO PLUS foam and carbon plate."
  },
  {
    brand: "Asics",
    model: "Magic Speed 4",
    category: "speed_training",
    weight: 7.4,
    heelStackHeight: 36,
    forefootStackHeight: 31,
    heelToToeDrop: 5,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 180,
    bestFor: ["tempo", "speed_work", "racing"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 3.2,
    responsivenessRating: 4.5,
    comfortRating: 3.8,
    releaseYear: 2024,
    description: "Affordable carbon racer for workouts and shorter races."
  },
  // NEW BALANCE
  {
    brand: "New Balance",
    model: "Fresh Foam X 1080v14",
    category: "daily_trainer",
    weight: 10.3,
    heelStackHeight: 34,
    forefootStackHeight: 28,
    heelToToeDrop: 6,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 165,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 230,
    durabilityRating: 4.0,
    responsivenessRating: 3.5,
    comfortRating: 4.8,
    releaseYear: 2024,
    description: "Premium cushioned trainer with Fresh Foam X midsole. All-day comfort."
  },
  {
    brand: "New Balance",
    model: "Fresh Foam X More v4",
    category: "recovery",
    weight: 11.6,
    heelStackHeight: 38,
    forefootStackHeight: 34,
    heelToToeDrop: 4,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 175,
    bestFor: ["easy_runs", "recovery"],
    minRunnerWeight: 160,
    maxRunnerWeight: 280,
    durabilityRating: 4.2,
    responsivenessRating: 2.8,
    comfortRating: 5.0,
    releaseYear: 2023,
    description: "Maximum cushioned recovery shoe with ultra-plush Fresh Foam X."
  },
  {
    brand: "New Balance",
    model: "FuelCell SuperComp Elite v4",
    category: "racing",
    weight: 7.0,
    heelStackHeight: 39.5,
    forefootStackHeight: 31.5,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 230,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 175,
    durabilityRating: 2.5,
    responsivenessRating: 4.8,
    comfortRating: 3.6,
    releaseYear: 2024,
    description: "Elite carbon racer with FuelCell foam for race day performance."
  },
  {
    brand: "New Balance",
    model: "FuelCell Rebel v4",
    category: "speed_training",
    weight: 7.8,
    heelStackHeight: 30,
    forefootStackHeight: 24,
    heelToToeDrop: 6,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 140,
    bestFor: ["tempo", "speed_work", "easy_runs"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 3.5,
    responsivenessRating: 4.5,
    comfortRating: 4.2,
    releaseYear: 2024,
    description: "Light, fast, and fun trainer for uptempo workouts and daily runs."
  },
  {
    brand: "New Balance",
    model: "FuelCell Propel v5",
    category: "daily_trainer",
    weight: 9.6,
    heelStackHeight: 32,
    forefootStackHeight: 26,
    heelToToeDrop: 6,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 110,
    bestFor: ["easy_runs", "tempo"],
    minRunnerWeight: 120,
    maxRunnerWeight: 200,
    durabilityRating: 4.0,
    responsivenessRating: 4.0,
    comfortRating: 4.0,
    releaseYear: 2024,
    description: "Affordable FuelCell trainer for responsive daily miles."
  },
  // SAUCONY
  {
    brand: "Saucony",
    model: "Ride 17",
    category: "daily_trainer",
    weight: 9.5,
    heelStackHeight: 35,
    forefootStackHeight: 27,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 140,
    bestFor: ["easy_runs", "long_runs", "tempo"],
    minRunnerWeight: 130,
    maxRunnerWeight: 210,
    durabilityRating: 4.2,
    responsivenessRating: 3.8,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "Versatile PWRRUN+ trainer for everyday miles. Smooth and reliable."
  },
  {
    brand: "Saucony",
    model: "Triumph 22",
    category: "long_run",
    weight: 10.2,
    heelStackHeight: 38,
    forefootStackHeight: 28,
    heelToToeDrop: 10,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 160,
    bestFor: ["long_runs", "easy_runs", "recovery"],
    minRunnerWeight: 150,
    maxRunnerWeight: 240,
    durabilityRating: 4.0,
    responsivenessRating: 3.3,
    comfortRating: 4.8,
    releaseYear: 2024,
    description: "Max cushioned trainer with PWRRUN PB foam for plush, long runs."
  },
  {
    brand: "Saucony",
    model: "Endorphin Pro 4",
    category: "racing",
    weight: 7.2,
    heelStackHeight: 39.5,
    forefootStackHeight: 31.5,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 225,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 175,
    durabilityRating: 2.5,
    responsivenessRating: 4.9,
    comfortRating: 3.6,
    releaseYear: 2024,
    description: "Elite carbon racer with PWRRUN PB foam for race day speed."
  },
  {
    brand: "Saucony",
    model: "Endorphin Speed 4",
    category: "speed_training",
    weight: 7.8,
    heelStackHeight: 38,
    forefootStackHeight: 30,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: true,
    price: 170,
    bestFor: ["tempo", "speed_work", "racing"],
    minRunnerWeight: 110,
    maxRunnerWeight: 185,
    durabilityRating: 3.5,
    responsivenessRating: 4.5,
    comfortRating: 4.0,
    releaseYear: 2024,
    description: "Nylon plate tempo trainer with PWRRUN PB foam. Great for workouts and races."
  },
  {
    brand: "Saucony",
    model: "Kinvara 14",
    category: "speed_training",
    weight: 7.5,
    heelStackHeight: 28,
    forefootStackHeight: 24,
    heelToToeDrop: 4,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 120,
    bestFor: ["tempo", "speed_work", "easy_runs"],
    minRunnerWeight: 100,
    maxRunnerWeight: 170,
    durabilityRating: 3.5,
    responsivenessRating: 4.2,
    comfortRating: 4.0,
    releaseYear: 2023,
    description: "Light and natural feeling trainer for fast, minimal miles."
  },
  // ON
  {
    brand: "On",
    model: "Cloudmonster 2",
    category: "daily_trainer",
    weight: 10.0,
    heelStackHeight: 35,
    forefootStackHeight: 27,
    heelToToeDrop: 8,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 170,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 140,
    maxRunnerWeight: 220,
    durabilityRating: 4.0,
    responsivenessRating: 3.8,
    comfortRating: 4.3,
    releaseYear: 2024,
    description: "Max cushioned CloudTec trainer with bouncy Helion HF foam."
  },
  {
    brand: "On",
    model: "Cloudsurfer 7",
    category: "daily_trainer",
    weight: 9.5,
    heelStackHeight: 32,
    forefootStackHeight: 25,
    heelToToeDrop: 7,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 160,
    bestFor: ["easy_runs", "tempo"],
    minRunnerWeight: 120,
    maxRunnerWeight: 200,
    durabilityRating: 3.8,
    responsivenessRating: 4.0,
    comfortRating: 4.2,
    releaseYear: 2024,
    description: "Versatile trainer with CloudTec Phase cushioning system."
  },
  {
    brand: "On",
    model: "Cloudboom Echo 3",
    category: "racing",
    weight: 7.8,
    heelStackHeight: 39,
    forefootStackHeight: 33,
    heelToToeDrop: 6,
    cushioningLevel: "firm",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 290,
    bestFor: ["racing", "speed_work"],
    minRunnerWeight: 100,
    maxRunnerWeight: 175,
    durabilityRating: 2.5,
    responsivenessRating: 4.7,
    comfortRating: 3.5,
    releaseYear: 2023,
    description: "Elite carbon racer with Helion HF superfoam and Speedboard."
  },
  // ALTRA (Zero Drop)
  {
    brand: "Altra",
    model: "Torin 7",
    category: "daily_trainer",
    weight: 10.0,
    heelStackHeight: 30,
    forefootStackHeight: 30,
    heelToToeDrop: 0,
    cushioningLevel: "soft",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 150,
    bestFor: ["easy_runs", "long_runs"],
    minRunnerWeight: 130,
    maxRunnerWeight: 210,
    durabilityRating: 4.0,
    responsivenessRating: 3.2,
    comfortRating: 4.5,
    releaseYear: 2024,
    description: "Zero-drop cushioned trainer with wide toe box for natural foot positioning."
  },
  {
    brand: "Altra",
    model: "Escalante 4",
    category: "speed_training",
    weight: 8.5,
    heelStackHeight: 24,
    forefootStackHeight: 24,
    heelToToeDrop: 0,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: false,
    hasSuperFoam: false,
    price: 140,
    bestFor: ["tempo", "speed_work", "easy_runs"],
    minRunnerWeight: 110,
    maxRunnerWeight: 180,
    durabilityRating: 3.5,
    responsivenessRating: 4.0,
    comfortRating: 4.2,
    releaseYear: 2024,
    description: "Light zero-drop trainer for natural running and faster workouts."
  },
  {
    brand: "Altra",
    model: "Vanish Carbon 2",
    category: "racing",
    weight: 6.4,
    heelStackHeight: 38,
    forefootStackHeight: 38,
    heelToToeDrop: 0,
    cushioningLevel: "medium",
    stability: "neutral",
    hasCarbonPlate: true,
    hasSuperFoam: true,
    price: 260,
    bestFor: ["racing"],
    minRunnerWeight: 100,
    maxRunnerWeight: 170,
    durabilityRating: 2.0,
    responsivenessRating: 4.8,
    comfortRating: 3.5,
    releaseYear: 2024,
    description: "Zero-drop carbon racer with Altra EGO MAX foam. Unique in the market."
  }
];
