-- Generated by scripts/d1/generate.ts from shared/schema.ts. Do not edit by hand.

-- ISO-8601 UTC timestamps; JSON and arrays stored as validated TEXT.

CREATE TABLE "activities" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "strava_id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "distance" REAL NOT NULL,
  "moving_time" INTEGER NOT NULL,
  "total_elevation_gain" REAL NOT NULL,
  "average_speed" REAL NOT NULL,
  "max_speed" REAL NOT NULL,
  "average_heartrate" REAL,
  "max_heartrate" REAL,
  "start_date" TEXT NOT NULL,
  "type" TEXT NOT NULL DEFAULT 'Run',
  "calories" REAL,
  "average_cadence" REAL,
  "max_cadence" REAL,
  "average_watts" REAL,
  "max_watts" REAL,
  "suffer_score" INTEGER,
  "comments_count" INTEGER DEFAULT 0,
  "kudos_count" INTEGER DEFAULT 0,
  "achievement_count" INTEGER DEFAULT 0,
  "start_latitude" REAL,
  "start_longitude" REAL,
  "end_latitude" REAL,
  "end_longitude" REAL,
  "polyline" TEXT,
  "detailed_polyline" TEXT,
  "streams_data" TEXT,
  "laps_data" TEXT,
  "average_temp" REAL,
  "has_heartrate" INTEGER DEFAULT 0 CHECK ("has_heartrate" IN (0,1)),
  "device_watts" INTEGER DEFAULT 0 CHECK ("device_watts" IN (0,1)),
  "elapsed_time" INTEGER,
  "workout_type" INTEGER,
  "pr_count" INTEGER DEFAULT 0,
  "photo_count" INTEGER DEFAULT 0,
  "athlete_count" INTEGER DEFAULT 1,
  "timezone" TEXT,
  "gear_id" TEXT,
  "elev_high" REAL,
  "elev_low" REAL,
  "hydration_status" TEXT DEFAULT 'none',
  "hydration_missing" TEXT CHECK ("hydration_missing" IS NULL OR json_valid("hydration_missing")),
  "hydrated_at" TEXT,
  "hydrate_attempts" INTEGER DEFAULT 0,
  "last_hydrate_error" TEXT,
  "cached_grade" TEXT,
  "cached_grade_updated_at" TEXT,
  "locked_for_free" INTEGER DEFAULT 0 CHECK ("locked_for_free" IN (0,1)),
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "activity_features" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "activity_id" INTEGER NOT NULL UNIQUE,
  "user_id" INTEGER NOT NULL,
  "aerobic_decoupling" REAL,
  "pace_at_hr_efficiency" REAL,
  "pacing_stability" REAL,
  "cadence_variability" REAL,
  "power_variability" REAL,
  "quality_score" REAL,
  "quality_flags" TEXT CHECK ("quality_flags" IS NULL OR json_valid("quality_flags")),
  "run_type" TEXT,
  "effort_bucket" TEXT,
  "computed_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "activity_route_map" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "activity_id" INTEGER NOT NULL,
  "route_id" INTEGER NOT NULL,
  "match_confidence" REAL DEFAULT 1,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "agent_runs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "run_type" TEXT NOT NULL,
  "triggered_by" TEXT NOT NULL,
  "activity_id" INTEGER,
  "dedupe_key" TEXT NOT NULL UNIQUE,
  "status" TEXT DEFAULT 'pending',
  "stages_completed" TEXT CHECK ("stages_completed" IS NULL OR json_valid("stages_completed")),
  "input_snapshot" TEXT CHECK ("input_snapshot" IS NULL OR json_valid("input_snapshot")),
  "output_recap_id" INTEGER,
  "output_notification_ids" TEXT CHECK ("output_notification_ids" IS NULL OR json_valid("output_notification_ids")),
  "prompt_version" TEXT,
  "metrics_version" TEXT,
  "duration_ms" INTEGER,
  "tokens_used" INTEGER,
  "error_message" TEXT,
  "retry_count" INTEGER DEFAULT 0,
  "started_at" TEXT,
  "completed_at" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "ai_conversations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "title" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "ai_insights" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "type" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "confidence" REAL NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "ai_messages" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "conversation_id" INTEGER NOT NULL,
  "role" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "feedback" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "api_keys" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "key_hash" TEXT NOT NULL,
  "key_hint" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "scopes" TEXT NOT NULL CHECK ("scopes" IS NULL OR json_valid("scopes")),
  "is_active" INTEGER DEFAULT 1 CHECK ("is_active" IN (0,1)),
  "last_used_at" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "athlete_profiles" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "sport" TEXT NOT NULL DEFAULT 'run',
  "baseline_weekly_mileage_km" REAL,
  "weekly_mileage_last_12_weeks" TEXT CHECK ("weekly_mileage_last_12_weeks" IS NULL OR json_valid("weekly_mileage_last_12_weeks")),
  "longest_recent_run_km" REAL,
  "avg_runs_per_week" REAL,
  "typical_easy_pace_min" REAL,
  "typical_easy_pace_max" REAL,
  "typical_tempo_pace" REAL,
  "typical_interval_pace" REAL,
  "hr_zones" TEXT CHECK ("hr_zones" IS NULL OR json_valid("hr_zones")),
  "max_hr" INTEGER,
  "resting_hr" INTEGER,
  "avg_elevation_gain_per_km" REAL,
  "preferred_run_days" TEXT CHECK ("preferred_run_days" IS NULL OR json_valid("preferred_run_days")),
  "injury_flags" TEXT CHECK ("injury_flags" IS NULL OR json_valid("injury_flags")),
  "max_days_per_week" INTEGER,
  "estimated_vdot" REAL,
  "estimated_race_times" TEXT CHECK ("estimated_race_times" IS NULL OR json_valid("estimated_race_times")),
  "last_computed_at" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "coach_agent_callback_events" (
  "delivery_id" TEXT PRIMARY KEY NOT NULL,
  "received_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "coach_agent_pilot_users" (
  "user_id" INTEGER PRIMARY KEY NOT NULL,
  "enabled" INTEGER NOT NULL DEFAULT 1 CHECK ("enabled" IN (0,1)),
  "added_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE cascade ON UPDATE no action
);

CREATE TABLE "coach_channel_bindings" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "binding_id" TEXT NOT NULL UNIQUE,
  "user_id" INTEGER NOT NULL,
  "channel" TEXT NOT NULL,
  "provider_user_hash" TEXT NOT NULL,
  "provider_chat_hash" TEXT NOT NULL,
  "mcp_token_id" INTEGER,
  "status" TEXT NOT NULL DEFAULT 'provisioning',
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "linked_at" TEXT,
  "revoked_at" TEXT,
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE cascade ON UPDATE no action,
  FOREIGN KEY ("mcp_token_id") REFERENCES "mcp_oauth_tokens" ("id") ON DELETE set null ON UPDATE no action
);

CREATE TABLE "coach_channel_link_tokens" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "channel" TEXT NOT NULL,
  "token_hash" TEXT NOT NULL UNIQUE,
  "expires_at" TEXT NOT NULL,
  "consumed_at" TEXT,
  "revoked_at" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE cascade ON UPDATE no action
);

CREATE TABLE "coach_recaps" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "activity_id" INTEGER NOT NULL,
  "strava_activity_id" TEXT NOT NULL,
  "recap_bullets" TEXT NOT NULL CHECK ("recap_bullets" IS NULL OR json_valid("recap_bullets")),
  "coaching_cue" TEXT NOT NULL,
  "next_step" TEXT NOT NULL,
  "next_step_rationale" TEXT NOT NULL,
  "confidence_flags" TEXT CHECK ("confidence_flags" IS NULL OR json_valid("confidence_flags")),
  "activity_name" TEXT NOT NULL,
  "activity_date" TEXT NOT NULL,
  "distance_km" REAL NOT NULL,
  "duration_mins" INTEGER NOT NULL,
  "coach_tone" TEXT NOT NULL,
  "linked_plan_day_id" INTEGER,
  "adherence_note" TEXT,
  "prompt_version" TEXT NOT NULL,
  "model_version" TEXT NOT NULL,
  "notification_sent" INTEGER DEFAULT 0 CHECK ("notification_sent" IN (0,1)),
  "viewed_at" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "deletion_feedback" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER,
  "user_email" TEXT,
  "reason" TEXT NOT NULL,
  "details" TEXT,
  "was_retained" INTEGER DEFAULT 0 CHECK ("was_retained" IN (0,1)),
  "subscription_plan" TEXT,
  "account_age_in_days" INTEGER,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "email_clicks" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "campaign" TEXT,
  "step" TEXT,
  "cta_key" TEXT,
  "job_id" INTEGER,
  "dedupe_key" TEXT,
  "clicked_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "source" TEXT
);

CREATE TABLE "email_jobs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "job_type" TEXT NOT NULL,
  "campaign" TEXT,
  "step" TEXT,
  "scheduled_at" TEXT NOT NULL,
  "status" TEXT DEFAULT 'pending',
  "dedupe_key" TEXT NOT NULL,
  "enrollment_id" INTEGER,
  "channel" TEXT NOT NULL DEFAULT 'email',
  "campaign_version" INTEGER NOT NULL DEFAULT 2,
  "experiment_variant" TEXT NOT NULL DEFAULT 'control',
  "metadata" TEXT CHECK ("metadata" IS NULL OR json_valid("metadata")),
  "sent_at" TEXT,
  "claimed_at" TEXT,
  "claimed_by" TEXT,
  "lease_expires_at" TEXT,
  "next_attempt_at" TEXT,
  "provider_message_id" TEXT,
  "delivered_at" TEXT,
  "bounced_at" TEXT,
  "complained_at" TEXT,
  "error_message" TEXT,
  "retry_count" INTEGER DEFAULT 0,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "email_waitlist" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "email" TEXT NOT NULL UNIQUE,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "launch_email_sent_at" TEXT
);

CREATE TABLE "feedback" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER,
  "user_email" TEXT,
  "type" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "status" TEXT DEFAULT 'new',
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "funnel_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER,
  "event" TEXT NOT NULL,
  "source" TEXT,
  "capability" TEXT,
  "activity_id" INTEGER,
  "billing_period" TEXT,
  "experiment_variant" TEXT,
  "properties" TEXT CHECK ("properties" IS NULL OR json_valid("properties")),
  "dedupe_key" TEXT NOT NULL UNIQUE,
  "occurred_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "goals" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "target_value" TEXT,
  "current_progress" REAL DEFAULT 0,
  "status" TEXT DEFAULT 'active',
  "source" TEXT DEFAULT 'recommendation',
  "completed_at" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "mcp_audit_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "event_type" TEXT NOT NULL,
  "user_id" INTEGER,
  "client_id" TEXT,
  "tool_name" TEXT,
  "success" INTEGER NOT NULL CHECK ("success" IN (0,1)),
  "error_code" TEXT,
  "duration_ms" INTEGER,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "mcp_oauth_authorization_codes" (
  "code_hash" TEXT PRIMARY KEY NOT NULL,
  "user_id" INTEGER NOT NULL,
  "client_id" TEXT NOT NULL,
  "redirect_uri" TEXT NOT NULL,
  "scopes" TEXT NOT NULL CHECK ("scopes" IS NULL OR json_valid("scopes")),
  "resource" TEXT NOT NULL,
  "code_challenge" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "expires_at" TEXT NOT NULL,
  "consumed_at" TEXT
);

CREATE TABLE "mcp_oauth_clients" (
  "client_id" TEXT PRIMARY KEY NOT NULL,
  "client_name" TEXT NOT NULL,
  "redirect_uris" TEXT NOT NULL CHECK ("redirect_uris" IS NULL OR json_valid("redirect_uris")),
  "token_endpoint_auth_method" TEXT NOT NULL DEFAULT 'none',
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "disabled_at" TEXT
);

CREATE TABLE "mcp_oauth_requests" (
  "request_hash" TEXT PRIMARY KEY NOT NULL,
  "client_id" TEXT NOT NULL,
  "redirect_uri" TEXT NOT NULL,
  "scopes" TEXT NOT NULL CHECK ("scopes" IS NULL OR json_valid("scopes")),
  "state" TEXT NOT NULL,
  "resource" TEXT NOT NULL,
  "code_challenge" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "expires_at" TEXT NOT NULL,
  "consumed_at" TEXT
);

CREATE TABLE "mcp_oauth_tokens" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "access_token_hash" TEXT NOT NULL UNIQUE,
  "refresh_token_hash" TEXT NOT NULL UNIQUE,
  "user_id" INTEGER NOT NULL,
  "client_id" TEXT NOT NULL,
  "scopes" TEXT NOT NULL CHECK ("scopes" IS NULL OR json_valid("scopes")),
  "resource" TEXT NOT NULL,
  "access_expires_at" TEXT NOT NULL,
  "refresh_expires_at" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "last_used_at" TEXT,
  "revoked_at" TEXT
);

CREATE TABLE "mcp_rate_limits" (
  "key" TEXT PRIMARY KEY NOT NULL,
  "window_started_at" TEXT NOT NULL,
  "count" INTEGER NOT NULL DEFAULT 0,
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "notification_outbox" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "type" TEXT NOT NULL,
  "channel" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "data" TEXT CHECK ("data" IS NULL OR json_valid("data")),
  "scheduled_for" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "status" TEXT DEFAULT 'pending',
  "sent_at" TEXT,
  "error_message" TEXT,
  "retry_count" INTEGER DEFAULT 0,
  "processing_started_at" TEXT,
  "dedupe_key" TEXT,
  "respect_quiet_hours" INTEGER DEFAULT 1 CHECK ("respect_quiet_hours" IN (0,1)),
  "read_at" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "performance_logs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER,
  "endpoint" TEXT NOT NULL,
  "method" TEXT NOT NULL,
  "status_code" INTEGER NOT NULL,
  "elapsed_time" INTEGER NOT NULL,
  "user_agent" TEXT,
  "error_message" TEXT,
  "error_details" TEXT,
  "request_body" TEXT,
  "response_body" TEXT,
  "timestamp" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "plan_days" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "week_id" INTEGER NOT NULL,
  "plan_id" INTEGER NOT NULL,
  "date" TEXT NOT NULL,
  "day_of_week" TEXT NOT NULL,
  "workout_type" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "planned_distance_km" REAL,
  "planned_duration_mins" INTEGER,
  "target_pace" TEXT,
  "target_hr_zone" TEXT,
  "intensity" TEXT DEFAULT 'low',
  "planned_vert_gain_m" INTEGER,
  "is_back_to_back_long_run" INTEGER DEFAULT 0 CHECK ("is_back_to_back_long_run" IN (0,1)),
  "fueling_practice" INTEGER DEFAULT 0 CHECK ("fueling_practice" IN (0,1)),
  "goal_contribution" TEXT CHECK ("goal_contribution" IS NULL OR json_valid("goal_contribution")),
  "workout_structure" TEXT CHECK ("workout_structure" IS NULL OR json_valid("workout_structure")),
  "status" TEXT DEFAULT 'pending',
  "linked_activity_id" INTEGER,
  "actual_distance_km" REAL,
  "actual_duration_mins" INTEGER,
  "actual_pace" TEXT,
  "user_notes" TEXT,
  "perceived_effort" INTEGER,
  "was_adjusted" INTEGER DEFAULT 0 CHECK ("was_adjusted" IN (0,1)),
  "original_workout_type" TEXT,
  "original_distance_km" REAL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "plan_goals" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "plan_id" INTEGER NOT NULL,
  "goal_type" TEXT NOT NULL,
  "race_date" TEXT,
  "target_time" TEXT,
  "priority" TEXT NOT NULL DEFAULT 'primary',
  "terrain_type" TEXT DEFAULT 'road',
  "notes" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "plan_weeks" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "plan_id" INTEGER NOT NULL,
  "week_number" INTEGER NOT NULL,
  "week_start_date" TEXT NOT NULL,
  "week_end_date" TEXT NOT NULL,
  "planned_distance_km" REAL NOT NULL,
  "planned_duration_mins" INTEGER,
  "week_type" TEXT NOT NULL,
  "phase_name" TEXT,
  "planned_vert_gain_m" INTEGER,
  "planned_long_run_duration_mins" INTEGER,
  "goal_split" TEXT CHECK ("goal_split" IS NULL OR json_valid("goal_split")),
  "why_this_week" TEXT,
  "completed_distance_km" REAL DEFAULT 0,
  "completed_duration_mins" INTEGER DEFAULT 0,
  "adherence_score" REAL,
  "coach_notes" TEXT,
  "was_adjusted" INTEGER DEFAULT 0 CHECK ("was_adjusted" IN (0,1)),
  "adjustment_reason" TEXT,
  "adjusted_at" TEXT,
  "enriched" INTEGER DEFAULT 0 CHECK ("enriched" IN (0,1)),
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "push_subscriptions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "platform" TEXT NOT NULL DEFAULT 'web',
  "endpoint" TEXT,
  "p256dh" TEXT,
  "auth" TEXT,
  "native_token" TEXT,
  "user_agent" TEXT,
  "enabled" INTEGER DEFAULT 1 CHECK ("enabled" IN (0,1)),
  "last_used_at" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "refresh_tokens" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "token_hash" TEXT NOT NULL,
  "device_name" TEXT,
  "device_id" TEXT,
  "expires_at" TEXT NOT NULL,
  "is_revoked" INTEGER DEFAULT 0 CHECK ("is_revoked" IN (0,1)),
  "last_used_at" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "routes" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "route_key" TEXT NOT NULL,
  "name" TEXT,
  "start_geohash" TEXT NOT NULL,
  "end_geohash" TEXT NOT NULL,
  "path_cells" TEXT CHECK ("path_cells" IS NULL OR json_valid("path_cells")),
  "representative_polyline" TEXT,
  "avg_distance" REAL,
  "avg_elevation_gain" REAL,
  "run_count" INTEGER DEFAULT 0,
  "last_run_at" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "running_shoes" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "brand" TEXT NOT NULL,
  "model" TEXT NOT NULL,
  "slug" TEXT UNIQUE,
  "series_name" TEXT,
  "version_number" INTEGER,
  "category" TEXT NOT NULL,
  "weight" REAL NOT NULL,
  "heel_stack_height" REAL NOT NULL,
  "forefoot_stack_height" REAL NOT NULL,
  "heel_to_toe_drop" REAL NOT NULL,
  "cushioning_level" TEXT NOT NULL,
  "stability" TEXT NOT NULL,
  "has_carbon_plate" INTEGER DEFAULT 0 CHECK ("has_carbon_plate" IN (0,1)),
  "has_super_foam" INTEGER DEFAULT 0 CHECK ("has_super_foam" IN (0,1)),
  "price" REAL NOT NULL,
  "best_for" TEXT NOT NULL CHECK ("best_for" IS NULL OR json_valid("best_for")),
  "min_runner_weight" INTEGER,
  "max_runner_weight" INTEGER,
  "durability_rating" REAL NOT NULL,
  "responsiveness_rating" REAL NOT NULL,
  "comfort_rating" REAL NOT NULL,
  "release_year" INTEGER NOT NULL,
  "image_url" TEXT,
  "description" TEXT,
  "ai_resilience_score" REAL,
  "ai_mileage_estimate" TEXT,
  "ai_target_usage" TEXT,
  "ai_narrative" TEXT,
  "ai_faq" TEXT,
  "source_url" TEXT,
  "data_source" TEXT DEFAULT 'curated',
  "last_verified" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "shoe_comparisons" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "slug" TEXT NOT NULL UNIQUE,
  "shoe1_id" INTEGER NOT NULL,
  "shoe2_id" INTEGER NOT NULL,
  "comparison_type" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "meta_description" TEXT,
  "verdict" TEXT,
  "verdict_winner" TEXT,
  "verdict_reason" TEXT,
  "key_differences" TEXT,
  "best_for" TEXT,
  "view_count" INTEGER DEFAULT 0,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY ("shoe1_id") REFERENCES "running_shoes" ("id") ON DELETE no action ON UPDATE no action,
  FOREIGN KEY ("shoe2_id") REFERENCES "running_shoes" ("id") ON DELETE no action ON UPDATE no action
);

CREATE TABLE "similar_runs_cache" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "activity_id" INTEGER NOT NULL UNIQUE,
  "user_id" INTEGER NOT NULL,
  "similar_activity_ids" TEXT NOT NULL CHECK ("similar_activity_ids" IS NULL OR json_valid("similar_activity_ids")),
  "similarity_scores" TEXT NOT NULL CHECK ("similarity_scores" IS NULL OR json_valid("similarity_scores")),
  "baseline_pace" REAL,
  "baseline_hr" REAL,
  "baseline_drift" REAL,
  "baseline_pacing_stability" REAL,
  "pace_vs_baseline" REAL,
  "hr_vs_baseline" REAL,
  "drift_vs_baseline" REAL,
  "pacing_vs_baseline" REAL,
  "computed_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "expires_at" TEXT
);

CREATE TABLE "strava_webhook_logs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "event_id" TEXT,
  "event_type" TEXT NOT NULL,
  "object_type" TEXT NOT NULL,
  "object_id" TEXT NOT NULL,
  "athlete_id" TEXT NOT NULL,
  "subscription_id" INTEGER,
  "status" TEXT NOT NULL DEFAULT 'received',
  "error_message" TEXT,
  "raw_payload" TEXT,
  "received_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "processed_at" TEXT
);

CREATE TABLE "system_settings" (
  "key" TEXT PRIMARY KEY NOT NULL,
  "value" TEXT NOT NULL,
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "training_plans_v2" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "goal_type" TEXT NOT NULL,
  "race_date" TEXT,
  "target_time" TEXT,
  "terrain_type" TEXT DEFAULT 'road',
  "days_per_week" INTEGER NOT NULL DEFAULT 4,
  "preferred_long_run_day" TEXT DEFAULT 'sunday',
  "preferred_days" TEXT CHECK ("preferred_days" IS NULL OR json_valid("preferred_days")),
  "allow_cross_training" INTEGER DEFAULT 1 CHECK ("allow_cross_training" IN (0,1)),
  "pace_based_workouts" INTEGER DEFAULT 1 CHECK ("pace_based_workouts" IN (0,1)),
  "status" TEXT DEFAULT 'draft',
  "total_weeks" INTEGER NOT NULL,
  "current_week" INTEGER DEFAULT 1,
  "coach_notes" TEXT,
  "generation_prompt" TEXT,
  "enrichment_status" TEXT DEFAULT 'pending',
  "enriched_weeks" INTEGER DEFAULT 0,
  "enrichment_error" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "training_plans" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "weeks" INTEGER NOT NULL,
  "plan_data" TEXT NOT NULL CHECK ("plan_data" IS NULL OR json_valid("plan_data")),
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "user_campaigns" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "campaign" TEXT NOT NULL,
  "state" TEXT DEFAULT 'active',
  "current_step" INTEGER DEFAULT 1,
  "campaign_version" INTEGER NOT NULL DEFAULT 2,
  "experiment_variant" TEXT NOT NULL DEFAULT 'control',
  "is_holdout" INTEGER NOT NULL DEFAULT 0 CHECK ("is_holdout" IN (0,1)),
  "entered_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "exited_at" TEXT,
  "exit_reason" TEXT,
  "last_email_sent_at" TEXT,
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "users" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "email" TEXT UNIQUE,
  "password" TEXT,
  "first_name" TEXT,
  "last_name" TEXT,
  "username" TEXT UNIQUE,
  "strava_access_token" TEXT,
  "strava_refresh_token" TEXT,
  "strava_athlete_id" TEXT,
  "strava_connected" INTEGER DEFAULT 0 CHECK ("strava_connected" IN (0,1)),
  "strava_has_write_scope" INTEGER DEFAULT 0 CHECK ("strava_has_write_scope" IN (0,1)),
  "strava_branding_enabled" INTEGER DEFAULT 0 CHECK ("strava_branding_enabled" IN (0,1)),
  "strava_branding_template" TEXT DEFAULT '🏃 Runner Score: {score} | {insight}: Analyzed with RunAnalytics',
  "unit_preference" TEXT DEFAULT 'miles',
  "activity_view_mode" TEXT DEFAULT 'story',
  "is_admin" INTEGER DEFAULT 0 CHECK ("is_admin" IN (0,1)),
  "last_sync_at" TEXT,
  "sync_status" TEXT DEFAULT 'idle',
  "sync_progress" INTEGER DEFAULT 0,
  "sync_total" INTEGER DEFAULT 0,
  "sync_error" TEXT,
  "last_incremental_since" TEXT,
  "strava_webhook_paused_at" TEXT,
  "dormancy_notice_sent_at" TEXT,
  "needs_historical_backfill" INTEGER DEFAULT 0 CHECK ("needs_historical_backfill" IN (0,1)),
  "reset_token" TEXT,
  "reset_token_expiry" TEXT,
  "stripe_customer_id" TEXT,
  "stripe_subscription_id" TEXT,
  "subscription_status" TEXT DEFAULT 'active',
  "subscription_plan" TEXT DEFAULT 'free',
  "trial_ends_at" TEXT,
  "subscription_ends_at" TEXT,
  "monthly_insight_count" INTEGER DEFAULT 0,
  "insight_count_reset_at" TEXT,
  "coach_onboarding_completed" INTEGER DEFAULT 0 CHECK ("coach_onboarding_completed" IN (0,1)),
  "coach_goal" TEXT,
  "coach_race_date" TEXT,
  "coach_target_time" TEXT,
  "coach_days_available" TEXT CHECK ("coach_days_available" IS NULL OR json_valid("coach_days_available")),
  "coach_weekly_mileage_cap" REAL,
  "coach_tone" TEXT DEFAULT 'direct',
  "coach_notify_recap" INTEGER DEFAULT 1 CHECK ("coach_notify_recap" IN (0,1)),
  "coach_notify_weekly_summary" INTEGER DEFAULT 1 CHECK ("coach_notify_weekly_summary" IN (0,1)),
  "notify_post_run" INTEGER DEFAULT 1 CHECK ("notify_post_run" IN (0,1)),
  "post_run_email_frequency" TEXT DEFAULT 'every_run',
  "last_post_run_email_at" TEXT,
  "coach_quiet_hours_start" INTEGER,
  "coach_quiet_hours_end" INTEGER,
  "last_coach_sync_at" TEXT,
  "coach_enabled" INTEGER DEFAULT 1 CHECK ("coach_enabled" IN (0,1)),
  "coach_timezone" TEXT DEFAULT 'UTC',
  "coach_daily_briefing_enabled" INTEGER DEFAULT 1 CHECK ("coach_daily_briefing_enabled" IN (0,1)),
  "coach_daily_briefing_hour" INTEGER DEFAULT 7,
  "coach_weather_enabled" INTEGER DEFAULT 0 CHECK ("coach_weather_enabled" IN (0,1)),
  "coach_weather_location" TEXT CHECK ("coach_weather_location" IS NULL OR json_valid("coach_weather_location")),
  "coach_preferred_channel" TEXT DEFAULT 'email',
  "coach_snoozed_until" TEXT,
  "coach_daily_availability" TEXT,
  "coach_daily_availability_date" TEXT,
  "cached_recovery_state" TEXT CHECK ("cached_recovery_state" IS NULL OR json_valid("cached_recovery_state")),
  "recovery_calculated_at" TEXT,
  "activation_at" TEXT,
  "last_seen_at" TEXT,
  "marketing_opt_out" INTEGER DEFAULT 0 CHECK ("marketing_opt_out" IN (0,1)),
  "marketing_consent_status" TEXT DEFAULT 'unknown',
  "marketing_consented_at" TEXT,
  "marketing_unsubscribed_at" TEXT,
  "marketing_suppression_reason" TEXT,
  "marketing_consent_source" TEXT,
  "coach_questions_count_7d" INTEGER DEFAULT 0,
  "welcome_email_sent_at" TEXT,
  "onboarding_goal" TEXT,
  "onboarding_struggle" TEXT,
  "onboarding_days" TEXT,
  "onboarding_completed_at" TEXT,
  "premium_preview" TEXT CHECK ("premium_preview" IS NULL OR json_valid("premium_preview")),
  "premium_preview_created_at" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "workout_cache" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "fingerprint" TEXT NOT NULL UNIQUE,
  "goal_type" TEXT NOT NULL,
  "workout_type" TEXT NOT NULL,
  "quality_level" INTEGER NOT NULL,
  "week_type" TEXT NOT NULL,
  "distance_bucket" INTEGER NOT NULL,
  "vdot_bucket" INTEGER,
  "title" TEXT NOT NULL,
  "description_template" TEXT NOT NULL,
  "main_set_template" TEXT NOT NULL,
  "intervals_template" TEXT CHECK ("intervals_template" IS NULL OR json_valid("intervals_template")),
  "intensity" TEXT NOT NULL,
  "hit_count" INTEGER DEFAULT 0,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "last_used_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX "activities_user_id_idx" ON "activities" ("user_id");

CREATE INDEX "activities_start_date_idx" ON "activities" ("start_date");

CREATE INDEX "activities_user_id_start_date_idx" ON "activities" ("user_id","start_date");

CREATE INDEX "activity_features_activity_id_idx" ON "activity_features" ("activity_id");

CREATE INDEX "activity_features_user_id_idx" ON "activity_features" ("user_id");

CREATE INDEX "activity_route_map_activity_id_idx" ON "activity_route_map" ("activity_id");

CREATE INDEX "activity_route_map_route_id_idx" ON "activity_route_map" ("route_id");

CREATE INDEX "agent_runs_user_id_idx" ON "agent_runs" ("user_id");

CREATE INDEX "agent_runs_dedupe_key_idx" ON "agent_runs" ("dedupe_key");

CREATE INDEX "agent_runs_status_idx" ON "agent_runs" ("status");

CREATE INDEX "agent_runs_created_at_idx" ON "agent_runs" ("created_at");

CREATE INDEX "ai_conversations_user_id_idx" ON "ai_conversations" ("user_id");

CREATE INDEX "ai_conversations_updated_at_idx" ON "ai_conversations" ("updated_at");

CREATE INDEX "ai_insights_user_id_idx" ON "ai_insights" ("user_id");

CREATE INDEX "ai_insights_created_at_idx" ON "ai_insights" ("created_at");

CREATE INDEX "ai_insights_user_id_type_idx" ON "ai_insights" ("user_id","type");

CREATE INDEX "ai_messages_conversation_id_idx" ON "ai_messages" ("conversation_id");

CREATE INDEX "ai_messages_created_at_idx" ON "ai_messages" ("created_at");

CREATE INDEX "api_keys_user_id_idx" ON "api_keys" ("user_id");

CREATE INDEX "athlete_profiles_user_sport_idx" ON "athlete_profiles" ("user_id","sport");

CREATE INDEX "coach_channel_bindings_user_idx" ON "coach_channel_bindings" ("user_id");

CREATE INDEX "coach_channel_bindings_provider_user_idx" ON "coach_channel_bindings" ("provider_user_hash");

CREATE INDEX "coach_channel_bindings_provider_chat_idx" ON "coach_channel_bindings" ("provider_chat_hash");

CREATE UNIQUE INDEX "coach_channel_bindings_active_user_channel_uidx" ON "coach_channel_bindings" ("user_id","channel") WHERE "revoked_at" IS NULL;

CREATE UNIQUE INDEX "coach_channel_bindings_active_provider_user_uidx" ON "coach_channel_bindings" ("channel","provider_user_hash") WHERE "revoked_at" IS NULL;

CREATE UNIQUE INDEX "coach_channel_bindings_active_provider_chat_uidx" ON "coach_channel_bindings" ("channel","provider_chat_hash") WHERE "revoked_at" IS NULL;

CREATE INDEX "coach_channel_link_tokens_user_idx" ON "coach_channel_link_tokens" ("user_id");

CREATE INDEX "coach_channel_link_tokens_expiry_idx" ON "coach_channel_link_tokens" ("expires_at");

CREATE INDEX "coach_recaps_user_id_idx" ON "coach_recaps" ("user_id");

CREATE INDEX "coach_recaps_activity_id_idx" ON "coach_recaps" ("activity_id");

CREATE INDEX "coach_recaps_user_activity_idx" ON "coach_recaps" ("user_id","activity_id");

CREATE INDEX "coach_recaps_created_at_idx" ON "coach_recaps" ("created_at");

CREATE INDEX "email_clicks_user_id_idx" ON "email_clicks" ("user_id");

CREATE INDEX "email_clicks_campaign_step_idx" ON "email_clicks" ("campaign","step");

CREATE UNIQUE INDEX "email_clicks_dedupe_key_idx" ON "email_clicks" ("dedupe_key");

CREATE INDEX "email_jobs_user_id_idx" ON "email_jobs" ("user_id");

CREATE INDEX "email_jobs_status_idx" ON "email_jobs" ("status");

CREATE INDEX "email_jobs_scheduled_at_idx" ON "email_jobs" ("scheduled_at");

CREATE UNIQUE INDEX "email_jobs_dedupe_key_idx" ON "email_jobs" ("dedupe_key");

CREATE INDEX "email_jobs_claim_idx" ON "email_jobs" ("status","scheduled_at","next_attempt_at","lease_expires_at");

CREATE INDEX "funnel_events_event_idx" ON "funnel_events" ("event");

CREATE INDEX "funnel_events_user_id_idx" ON "funnel_events" ("user_id");

CREATE INDEX "funnel_events_occurred_at_idx" ON "funnel_events" ("occurred_at");

CREATE INDEX "mcp_audit_events_created_idx" ON "mcp_audit_events" ("created_at");

CREATE INDEX "mcp_audit_events_user_idx" ON "mcp_audit_events" ("user_id");

CREATE INDEX "mcp_audit_events_client_idx" ON "mcp_audit_events" ("client_id");

CREATE INDEX "mcp_oauth_codes_user_idx" ON "mcp_oauth_authorization_codes" ("user_id");

CREATE INDEX "mcp_oauth_codes_client_idx" ON "mcp_oauth_authorization_codes" ("client_id");

CREATE INDEX "mcp_oauth_codes_expiry_idx" ON "mcp_oauth_authorization_codes" ("expires_at");

CREATE INDEX "mcp_oauth_requests_client_idx" ON "mcp_oauth_requests" ("client_id");

CREATE INDEX "mcp_oauth_requests_expiry_idx" ON "mcp_oauth_requests" ("expires_at");

CREATE INDEX "mcp_oauth_tokens_access_idx" ON "mcp_oauth_tokens" ("access_token_hash");

CREATE INDEX "mcp_oauth_tokens_refresh_idx" ON "mcp_oauth_tokens" ("refresh_token_hash");

CREATE INDEX "mcp_oauth_tokens_user_client_idx" ON "mcp_oauth_tokens" ("user_id","client_id");

CREATE INDEX "notification_outbox_user_id_idx" ON "notification_outbox" ("user_id");

CREATE INDEX "notification_outbox_status_idx" ON "notification_outbox" ("status");

CREATE INDEX "notification_outbox_scheduled_for_idx" ON "notification_outbox" ("scheduled_for");

CREATE INDEX "notification_outbox_dedupe_key_idx" ON "notification_outbox" ("dedupe_key");

CREATE INDEX "plan_days_week_id_idx" ON "plan_days" ("week_id");

CREATE INDEX "plan_days_plan_id_idx" ON "plan_days" ("plan_id");

CREATE INDEX "plan_days_date_idx" ON "plan_days" ("date");

CREATE INDEX "plan_days_linked_activity_idx" ON "plan_days" ("linked_activity_id");

CREATE INDEX "plan_goals_plan_id_idx" ON "plan_goals" ("plan_id");

CREATE INDEX "plan_weeks_plan_id_idx" ON "plan_weeks" ("plan_id");

CREATE INDEX "plan_weeks_week_start_idx" ON "plan_weeks" ("week_start_date");

CREATE INDEX "push_subscriptions_user_id_idx" ON "push_subscriptions" ("user_id");

CREATE INDEX "push_subscriptions_endpoint_idx" ON "push_subscriptions" ("endpoint");

CREATE INDEX "push_subscriptions_native_token_idx" ON "push_subscriptions" ("native_token");

CREATE INDEX "refresh_tokens_user_id_idx" ON "refresh_tokens" ("user_id");

CREATE INDEX "refresh_tokens_token_hash_idx" ON "refresh_tokens" ("token_hash");

CREATE INDEX "routes_user_id_idx" ON "routes" ("user_id");

CREATE INDEX "routes_route_key_idx" ON "routes" ("route_key");

CREATE INDEX "running_shoes_brand_idx" ON "running_shoes" ("brand");

CREATE INDEX "running_shoes_category_idx" ON "running_shoes" ("category");

CREATE INDEX "running_shoes_slug_idx" ON "running_shoes" ("slug");

CREATE INDEX "running_shoes_series_idx" ON "running_shoes" ("series_name");

CREATE INDEX "shoe_comparisons_slug_idx" ON "shoe_comparisons" ("slug");

CREATE INDEX "shoe_comparisons_shoe1_idx" ON "shoe_comparisons" ("shoe1_id");

CREATE INDEX "shoe_comparisons_shoe2_idx" ON "shoe_comparisons" ("shoe2_id");

CREATE INDEX "shoe_comparisons_type_idx" ON "shoe_comparisons" ("comparison_type");

CREATE INDEX "similar_runs_cache_activity_id_idx" ON "similar_runs_cache" ("activity_id");

CREATE INDEX "similar_runs_cache_user_id_idx" ON "similar_runs_cache" ("user_id");

CREATE INDEX "strava_wh_logs_athlete_idx" ON "strava_webhook_logs" ("athlete_id");

CREATE INDEX "strava_wh_logs_status_idx" ON "strava_webhook_logs" ("status");

CREATE INDEX "strava_wh_logs_received_idx" ON "strava_webhook_logs" ("received_at");

CREATE INDEX "training_plans_v2_user_id_idx" ON "training_plans_v2" ("user_id");

CREATE INDEX "training_plans_v2_status_idx" ON "training_plans_v2" ("status");

CREATE INDEX "user_campaigns_user_id_idx" ON "user_campaigns" ("user_id");

CREATE INDEX "user_campaigns_campaign_idx" ON "user_campaigns" ("campaign");

CREATE INDEX "user_campaigns_state_idx" ON "user_campaigns" ("state");

CREATE UNIQUE INDEX "user_campaigns_user_campaign_unique_idx" ON "user_campaigns" ("user_id","campaign","campaign_version");

CREATE UNIQUE INDEX "user_campaigns_one_active_idx" ON "user_campaigns" ("user_id") WHERE "state" = 'active';

CREATE INDEX "workout_cache_fingerprint_idx" ON "workout_cache" ("fingerprint");

CREATE INDEX "workout_cache_goal_type_idx" ON "workout_cache" ("goal_type","workout_type");
