// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-variants/AICoachConvo.tsx": () => import("../components/mockups/landing-variants/AICoachConvo.tsx"),
  "./components/mockups/landing-variants/AntiSummit.tsx": () => import("../components/mockups/landing-variants/AntiSummit.tsx"),
  "./components/mockups/landing-variants/OutcomeProof.tsx": () => import("../components/mockups/landing-variants/OutcomeProof.tsx"),
  "./components/mockups/landing-variants/StravaFirst.tsx": () => import("../components/mockups/landing-variants/StravaFirst.tsx")
};
