import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { buildApplicationSchema, quote } from './schema';

const tables = buildApplicationSchema();
const directory = resolve('apps/d1-migration/migrations');
mkdirSync(directory, { recursive: true });
writeFileSync(resolve(directory, '0001_application.sql'), [
  '-- Generated by scripts/d1/generate.ts from shared/schema.ts. Do not edit by hand.',
  '-- ISO-8601 UTC timestamps; JSON and arrays stored as validated TEXT.',
  ...tables.map(table => table.ddl), ...tables.flatMap(table => table.indexes),
].join('\n\n')+'\n');
const activity = tables.find(table => table.name === 'activities')!;
const bytes = `${64 + activity.columns.length * 9} + ` + activity.columns.map(column =>
  `coalesce(length(CAST(NEW.${quote(column.name)} AS BLOB)),0)`).join(' + ');
const guard=(operation:string,budget:number)=>`CREATE TRIGGER activity_size_${operation.toLowerCase()} BEFORE ${operation} ON activities\nWHEN (${bytes}) > ${budget}\nBEGIN SELECT RAISE(ABORT,'D1_ACTIVITY_TOO_LARGE'); END;`;
writeFileSync(resolve(directory,'0004_activity_size_guard.sql'),[
  '-- Generated full-row guards. Do not drop existing activity data on oversized updates.',
  ...['INSERT','UPDATE'].map(operation => guard(operation,1900000)),
].join('\n\n'));
writeFileSync(resolve(directory,'0005_activity_import_headroom.sql'),[
  '-- Retained source rows reach 1,973,114 bytes; preserve them while keeping 2 KB headroom.',
  'DROP TRIGGER activity_size_insert;', 'DROP TRIGGER activity_size_update;',
  ...['INSERT','UPDATE'].map(operation=>guard(operation,1998000)),
].join('\n\n'));
console.log(`Generated ${tables.length} application tables; supplemental tables are in 0002.`);
