import ts from 'typescript';
import {readFileSync,writeFileSync} from 'node:fs';

const source=ts.createSourceFile('schema.ts',readFileSync('shared/schema.ts','utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);
const result=ts.transform(source,[(context)=>{
  const f=context.factory;
  const visit:ts.Visitor=(node)=>{
    if(ts.isImportDeclaration(node)&&ts.isStringLiteral(node.moduleSpecifier)&&node.moduleSpecifier.text==='drizzle-orm/pg-core'){
      return f.updateImportDeclaration(node,node.modifiers,node.importClause,f.createStringLiteral('./d1-core'),node.attributes);
    }
    if(ts.isCallExpression(node)&&ts.isPropertyAccessExpression(node.expression)){
      const property=node.expression.name.text;
      if(property==='defaultNow'){
        return f.createCallExpression(f.createPropertyAccessExpression(ts.visitNode(node.expression.expression,visit) as ts.Expression,'default'),undefined,[
          f.createTaggedTemplateExpression(f.createIdentifier('sql'),undefined,f.createNoSubstitutionTemplateLiteral("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))")),
        ]);
      }
      if(property==='primaryKey'&&ts.isCallExpression(node.expression.expression)
        &&ts.isIdentifier(node.expression.expression.expression)&&node.expression.expression.expression.text==='serial'){
        return f.updateCallExpression(node,node.expression,node.typeArguments,[f.createObjectLiteralExpression([
          f.createPropertyAssignment('autoIncrement',f.createTrue()),
        ])]);
      }
      if(property==='array'&&ts.isCallExpression(node.expression.expression)
        &&ts.isIdentifier(node.expression.expression.expression)&&node.expression.expression.expression.text==='text'){
        const base=node.expression.expression;
        if(!ts.isCallExpression(base)||!ts.isIdentifier(base.expression)||base.expression.text!=='text'||base.arguments.length!==1)throw new Error('ARRAY_CONVERSION_REQUIRES_REVIEW');
        const jsonText=f.updateCallExpression(base,base.expression,base.typeArguments,[...base.arguments,f.createObjectLiteralExpression([f.createPropertyAssignment('mode',f.createStringLiteral('json'))])]);
        return f.createCallExpression(f.createPropertyAccessExpression(jsonText,'$type'),[f.createArrayTypeNode(f.createKeywordTypeNode(ts.SyntaxKind.StringKeyword))],[]);
      }
    }
    return ts.visitEachChild(node,visit,context);
  };
  return (file)=>ts.visitNode(file,visit) as ts.SourceFile;
}]);
const printed=ts.createPrinter().printFile(result.transformed[0]);
writeFileSync('shared/schema.d1.ts','// GENERATED by scripts/d1/generate-model.ts. Edit shared/schema.ts, then regenerate.\n'+printed);
result.dispose();
console.log('Generated typed SQLite schema; production PostgreSQL schema unchanged.');
