export type EditorialTopic = "training" | "ai" | "tools";

export interface EditorialPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  dateLabel: string;
  readTime: string;
  category: string;
  topic: EditorialTopic;
  lede: string;
  sections: Array<{ id: string; title: string; html: string }>;
  faqs: Array<{ question: string; answer: string }>;
  sources: Array<{ label: string; href: string }>;
}

export const editorialPosts: EditorialPost[] = [
  {
    slug: "heart-rate-drift-aerobic-decoupling",
    title: "Heart Rate Drift and Aerobic Decoupling Explained",
    description: "Learn what heart-rate drift means, how aerobic decoupling is calculated, which runs are suitable, and how to avoid misleading conclusions.",
    date: "2026-08-07",
    dateLabel: "August 7, 2026",
    readTime: "9 min read",
    category: "Running Analytics",
    topic: "training",
    lede: "Heart rate often rises during a steady run even when pace stays unchanged. Aerobic decoupling turns that relationship into a comparison, but the number is useful only when the route, effort and data are suitable.",
    sections: [
      { id: "meaning", title: "What heart-rate drift actually measures", html: `<p>During prolonged steady exercise, heart rate can rise even when external work stays similar. Researchers describe cardiovascular drift as a collection of changes that can include rising heart rate and falling stroke volume. Reviews by Coyle and González-Alonso and, more recently, Souissi and colleagues show that temperature regulation, circulating blood volume, sympathetic activity and exercise duration can all contribute. There is no single mechanism that explains every run.</p><p>For runners, <strong>aerobic decoupling is a field comparison</strong>: did the relationship between speed and heart rate deteriorate from one part of the run to another? It is not a direct measurement of VO₂max, lactate threshold, mitochondrial density or injury risk. Those require different measurements.</p><p>The distinction matters. “Cardiac drift” describes a physiological response; “decoupling” is a calculation applied to recorded pace or power and heart rate. A watch can calculate the latter without proving the cause of the former.</p>` },
      { id: "physiology", title: "Why heart rate can rise at the same pace", html: `<p>Several processes can overlap. As core and skin temperature rise, the cardiovascular system must support both working muscle and heat dissipation. Sweat loss may reduce plasma volume. Stroke volume can fall, so heart rate rises to help preserve cardiac output. At the same time, fatigue can alter running economy and recruit muscle differently.</p><p>A field study of 17 distance runners completing 12 km in warm conditions found heart rate and intestinal temperature rose more as body-mass loss increased during controlled submaximal running. That does not mean every percentage of drift is dehydration: it shows why weather and fluid status must be recorded before interpreting the number.</p><table><thead><tr><th>Possible contributor</th><th>What you may observe</th><th>What to check</th></tr></thead><tbody><tr><td>Heat accumulation</td><td>Heart rate rises while pace stays similar</td><td>Temperature, humidity, sun and clothing</td></tr><tr><td>Pace too ambitious</td><td>Heart rate rises and pace later falls</td><td>Opening effort and talk test</td></tr><tr><td>Fuel or fluid mismatch</td><td>Late fade, thirst or gastrointestinal symptoms</td><td>Practiced intake and run duration</td></tr><tr><td>Terrain or wind</td><td>Efficiency changes abruptly by segment</td><td>Elevation and direction</td></tr><tr><td>Sensor error</td><td>Spikes, dropouts or implausible plateaus</td><td>Chest-strap contact and raw stream</td></tr></tbody></table>` },
      { id: "calculation", title: "How RunAnalytics calculates decoupling", html: `<p>The <a href="/tools/aerobic-decoupling-calculator">Aerobic Decoupling Calculator</a> divides a suitable run into equal halves and calculates speed-to-heart-rate efficiency for each:</p><p><strong>Efficiency = speed ÷ average heart rate</strong></p><p><strong>Decoupling (%) = [1 − (second-half efficiency ÷ first-half efficiency)] × 100</strong></p><p>With this sign convention, a positive number means efficiency faded; a negative number means it improved. Some platforms use pace instead of speed or reverse the sign. Comparing numbers across products without checking the formula can therefore produce the wrong conclusion.</p><p>The calculation should use moving segments consistently. Long traffic stops, missing heart-rate samples and mismatched split durations can bias the result even when the arithmetic is correct.</p>` },
      { id: "worked-example", title: "Worked example: same route, different conclusion", html: `<p>Suppose the first half averages 3.00 m/s at 150 bpm. Efficiency is 0.0200 m per beat. The second half averages 2.90 m/s at 155 bpm, giving 0.0187 m per beat. The calculation reports about <strong>6.5% positive fade</strong>.</p><p>That number says the recorded relationship weakened. It does not explain why. If the second half climbed into a headwind on a hot afternoon, fitness is not the cleanest explanation. If the route, temperature and effort were stable and the pattern repeats across several long runs, limited durability becomes more plausible.</p><p>A negative result is not automatically “better.” Starting too slowly, descending in the second half or a heart-rate sensor that reads high early can all create apparent improvement.</p>` },
      { id: "suitable-runs", title: "Choose a run that can answer the question", html: `<p>The best candidate is continuous, mostly flat and steady enough that the two halves represent similar work. A duration of roughly 60 minutes or more often gives drift time to develop, but there is no universal minimum. Shorter runs in heat can drift; very easy long runs may not.</p><ul><li><strong>Good candidate:</strong> steady aerobic run, stable surface, limited stopping, reliable heart rate.</li><li><strong>Poor candidate:</strong> intervals, progression run, race, hilly trail, stop-start city route or obvious sensor dropout.</li><li><strong>Comparable series:</strong> same route, similar duration, similar effort and similar environmental conditions.</li></ul><p>Exclude the warm-up only if you do so consistently. An early heart-rate ramp can inflate the apparent improvement in the second half.</p>` },
      { id: "interpretation", title: "Interpretation without rigid pass/fail rules", html: `<p>A five-percent reference is common in endurance coaching, but it is not a validated universal boundary between “aerobically fit” and “unfit.” Measurement noise alone can move a result near a threshold. Use categories as descriptive flags, not diagnoses.</p><table><thead><tr><th>Repeated observation</th><th>Reasonable interpretation</th><th>Premature conclusion</th></tr></thead><tbody><tr><td>Low fade in comparable steady runs</td><td>The chosen effort appears sustainable in those conditions</td><td>Your aerobic base is complete</td></tr><tr><td>Moderate fade only in heat</td><td>Environment materially affects cardiovascular demand</td><td>Your fitness suddenly declined</td></tr><tr><td>High fade across several controlled runs</td><td>Opening effort, durability, fueling and recovery deserve review</td><td>Add more intervals immediately</td></tr><tr><td>Erratic values</td><td>Data or route comparability is inadequate</td><td>Average the noise into a training decision</td></tr></tbody></table>` },
      { id: "tracking-protocol", title: "A four-run tracking protocol", html: `<ol><li>Select one repeatable aerobic route and duration.</li><li>Record temperature, wind, perceived effort, sleep, fueling and the heart-rate device used.</li><li>Run by controlled effort rather than forcing identical pace in materially different weather.</li><li>Repeat three or four times before judging the direction of the trend.</li></ol><p>Review decoupling beside weekly intensity distribution in the <a href="/blog/80-20-running-training-split">80/20 running guide</a>. If cadence also changes late in comparable runs, the <a href="/blog/running-cadence-by-pace">cadence-by-pace guide</a> explains how to separate speed effects from step-rate drift.</p>` },
      { id: "next-step", title: "What to do with the result", html: `<p>If fade repeats, first improve the test rather than intensify training: slow the opening pace, choose comparable conditions, verify the sensor and rehearse appropriate intake. Then examine whether easy days are genuinely easy and whether the long-run duration has progressed gradually.</p><p>Use the result alongside perceived effort, recent consistency and the <a href="/tools/training-split-analyzer">Training Split Analyzer</a>. Persistent unusual heart-rate responses with chest pain, dizziness, fainting or illness symptoms are not a coaching-metric problem; stop exercise and seek appropriate medical assessment.</p>` },
    ],
    faqs: [
      { question: "Is aerobic decoupling the same as cardiac drift?", answer: "They are closely related. Cardiac drift describes the heart-rate change; aerobic decoupling compares the change in heart rate relative to pace or power." },
      { question: "Is less than five percent always good?", answer: "No universal cutoff applies to every runner and condition. Use it as a reference and prioritize repeated comparisons on similar runs." },
      { question: "Can hills invalidate the result?", answer: "Large elevation or pace changes make a split-half comparison harder to interpret because the external work in each half is no longer comparable." },
      { question: "How many runs should I compare?", answer: "Use at least three comparable runs before treating a pattern as meaningful. Record weather, route, duration, effort and sensor quality." },
      { question: "Does high decoupling mean I should run harder?", answer: "No. First check pacing, heat, hills, fueling, recovery and data quality. Adding intensity automatically can worsen the problem the metric is flagging." },
    ],
    sources: [
      { label: "RunAnalytics Aerobic Decoupling Calculator", href: "/tools/aerobic-decoupling-calculator" },
      { label: "Souissi et al. (2021): A new perspective on cardiovascular drift", href: "https://pubmed.ncbi.nlm.nih.gov/34717912/" },
      { label: "Coyle & González-Alonso (2001): Cardiovascular drift during prolonged exercise", href: "https://pubmed.ncbi.nlm.nih.gov/11337829/" },
      { label: "Logan-Sprenger et al. (2010): Hydration and trail running in the heat", href: "https://pubmed.ncbi.nlm.nih.gov/20210618/" },
      { label: "Related guide: Calculate your actual training split", href: "/blog/80-20-running-training-split" },
    ],
  },
  {
    slug: "running-cadence-by-pace",
    title: "Running Cadence by Pace: Interpret Your Step Rate",
    description: "Understand how cadence changes with pace, height, terrain and fatigue, and why runners should not chase one universal steps-per-minute target.",
    date: "2026-08-07",
    dateLabel: "August 7, 2026",
    readTime: "9 min read",
    category: "Running Form",
    topic: "training",
    lede: "Cadence is the number of steps taken per minute. It is easy to measure and easy to misuse: pace, leg length, terrain and fatigue all change the number, so 180 steps per minute is not a universal target.",
    sections: [
      { id: "definition", title: "Cadence, step rate and stride frequency", html: `<p>Running cadence is normally displayed as <strong>steps per minute (spm)</strong>. One left and one right foot contact count as two steps. Some research and devices report stride frequency or single-leg revolutions, which is approximately half the familiar spm value. An 88-rpm device reading may therefore represent 176 spm rather than an exceptionally low cadence.</p><p>Cadence and stride length combine to produce speed. If pace increases, a runner can lengthen the stride, increase cadence or do both. That basic relationship is why a cadence number without pace context is incomplete.</p>` },
      { id: "context", title: "Cadence needs pace and runner context", html: `<p>Analysis of more than 16,000 hours of wearable data from 256 runners found a clear group relationship between stride frequency and running speed, alongside substantial individual differences. Leg length, body mass, age and running habits were associated with cadence at a given speed. Injury incidence and performance were not associated with one universal frequency in that dataset.</p><p>This does not provide a lookup table that predicts the correct cadence for an individual. It supports a better comparison: <strong>compare the same runner at similar pace, grade and surface</strong>. A recovery jog and a 5K race should not be expected to produce the same step rate.</p><table><thead><tr><th>Variable</th><th>Typical effect on the number</th><th>Analysis implication</th></tr></thead><tbody><tr><td>Faster pace</td><td>Cadence usually rises</td><td>Compare within a narrow pace band</td></tr><tr><td>Uphill running</td><td>Steps may shorten and quicken</td><td>Separate climbs from flat running</td></tr><tr><td>Downhill running</td><td>Stride and braking strategy change</td><td>Do not merge with flat segments</td></tr><tr><td>Fatigue</td><td>Cadence may rise, fall or stay stable</td><td>Check pace and stride length together</td></tr><tr><td>Runner dimensions</td><td>Preferred pattern differs</td><td>Avoid population-wide targets</td></tr></tbody></table>` },
      { id: "myth", title: "Why 180 spm is not a universal prescription", html: `<p>The 180-spm idea became popular after observations of competitive runners. It was never a controlled finding that every runner, at every speed, should take 180 steps per minute. Elite race observations also describe athletes moving quickly; applying the same number to a slow easy run removes the speed context.</p><p>A systematic review and meta-analysis of 37 cadence studies concluded that changing step rate alters several biomechanical variables, but evidence about injury and performance outcomes remained insufficient. Most studies examined immediate responses rather than long-term adaptation. That is a strong reason to reject promises that a particular cadence prevents injury or automatically improves economy.</p>` },
      { id: "biomechanics", title: "What cadence-change studies actually show", html: `<p>In a widely cited treadmill study, 45 healthy recreational runners ran at their preferred step rate and at changes of plus or minus 5% and 10% while speed stayed constant. Increasing step rate reduced energy absorbed at the knee in the tested conditions, with other joint-level changes at larger adjustments. This is evidence that cadence manipulation changes mechanics, not proof of fewer injuries.</p><p>The later meta-analysis found stronger evidence for changes such as reduced step length and peak knee flexion when cadence increased. Evidence for pain and function came from only a small injury literature, and the authors explicitly judged injury and performance conclusions insufficient. A clinician may use cadence retraining for a specific runner and condition; a generic web tool should not prescribe it from one average value.</p>` },
      { id: "drift", title: "What cadence drift can and cannot show", html: `<p>Late-run cadence change may accompany fatigue, slowing, climbing, surface changes or deliberate pacing. The <a href="/tools/cadence-analyzer">Cadence Analyzer</a> normalizes device data and describes within-run variability and late change. It cannot observe posture, foot strike, pain, joint loading or the reason a runner changed pace.</p><p>Use a two-question check:</p><ol><li><strong>Did cadence change because pace changed?</strong> Compare cadence only within similar pace segments.</li><li><strong>Did the environment change?</strong> Grade, surface, turns and wind can all alter the recorded pattern.</li></ol><p>If pace-to-heart-rate efficiency also deteriorated, compare the run using the <a href="/blog/heart-rate-drift-aerobic-decoupling">heart-rate drift guide</a>. Multiple aligned signals are more useful than naming cadence alone as “form fade.”</p>` },
      { id: "device-data", title: "Check the device before judging the runner", html: `<p>Device semantics are a frequent source of error. Strava activity data may express cadence as single-leg revolutions, while a watch display uses total steps. The value should be normalized once at the data boundary. Doubling it again in the interface turns a plausible 176 spm into an impossible 352 spm.</p><ul><li>Inspect raw samples for half-cadence values, zeroes and dropouts.</li><li>Confirm whether an average includes walking, stops or warm-up segments.</li><li>Use a foot pod or chest-based sensor comparison if wrist motion appears unreliable.</li><li>Do not compare treadmill and outdoor cadence until pace calibration is credible.</li></ul>` },
      { id: "worked-example", title: "Worked example: interpreting a late-run drop", html: `<p>A runner averages 168 spm at 5:30/km during the first 40 minutes and 162 spm during the last 20. On its own, that six-step drop sounds meaningful. But the final segment was 25 seconds per kilometer slower and included a climb. The valid conclusion is that cadence changed with the run; it is not evidence that mechanics broke down.</p><p>If a second run shows 168 to 162 spm while pace, grade and perceived effort remain similar, the pattern deserves further review. Even then, the next step is observation; video, symptoms, recovery and repeatability, not an automatic instruction to reach 180.</p>` },
      { id: "experiment", title: "A conservative cadence experiment", html: `<p>When there is a clear reason to test cadence, use the runner's own baseline. On a short, flat segment after warming up, compare the preferred rate with a cue roughly 3–5% higher. Keep speed similar and record comfort, breathing, perceived effort and any pain. Stop if the change creates tension or symptoms.</p><p>Repeat only if the first exposure is comfortable. Research shows metronome-based step cues can change cadence, but the ability to change a number is not the same as proving a benefit. Runners receiving gait retraining for pain should follow the plan of an appropriately qualified clinician.</p>` },
      { id: "actions", title: "How cadence fits into training decisions", html: `<p>For most healthy runners, cadence is best used as a descriptive trend. Build training around appropriate effort and recovery using the <a href="/tools/training-pace-calculator">Training Pace Calculator</a> and review intensity balance with the <a href="/blog/80-20-running-training-split">80/20 training guide</a>. Revisit cadence when it changes unexpectedly at the same pace, when a clinician assigns a gait intervention, or when device quality is in question.</p>` },
    ],
    faqs: [
      { question: "Is 180 steps per minute ideal?", answer: "No. Cadence varies with pace, body dimensions, terrain and individual mechanics. Consistency and comfort are usually more useful than a universal target." },
      { question: "Why does cadence fall late in a run?", answer: "It can fall because pace slows, fatigue changes mechanics, terrain changes or the device records poorly. Review all of those factors." },
      { question: "Should I deliberately increase cadence?", answer: "Only for a clear reason and preferably relative to your own baseline. Small, comfortable experiments are preferable to forcing a large immediate change." },
      { question: "Does a stable cadence prove good running form?", answer: "No. Stability describes the recorded step pattern. It cannot establish posture, joint loading, pain, efficiency or injury risk." },
      { question: "Why does my device show about 85 instead of 170?", answer: "It may be reporting single-leg revolutions or strides rather than total steps. Confirm the device definition before doubling the value, and normalize it only once." },
    ],
    sources: [
      { label: "RunAnalytics Cadence Analyzer", href: "/tools/cadence-analyzer" },
      { label: "Hoogkamer et al. (2019): Inter-individual stride-frequency differences in wearable data", href: "https://pubmed.ncbi.nlm.nih.gov/31079578/" },
      { label: "Heiderscheit et al. (2011): Step-rate manipulation and joint mechanics", href: "https://pubmed.ncbi.nlm.nih.gov/20581720/" },
      { label: "Anderson et al. (2022): Step-rate systematic review and meta-analysis", href: "https://pubmed.ncbi.nlm.nih.gov/36057913/" },
      { label: "Related guide: Heart-rate drift and aerobic decoupling", href: "/blog/heart-rate-drift-aerobic-decoupling" },
    ],
  },
  {
    slug: "80-20-running-training-split",
    title: "80/20 Running: Calculate Your Actual Training Split",
    description: "Learn how to calculate easy, moderate and hard training time, distinguish polarized from pyramidal training, and avoid rigid 80/20 rules.",
    date: "2026-08-07",
    dateLabel: "August 7, 2026",
    readTime: "9 min read",
    category: "Training Plans",
    topic: "training",
    lede: "The useful idea behind 80/20 running is not a perfect ratio. It is protecting enough low-intensity volume that harder work remains purposeful and recoverable.",
    sections: [
      { id: "meaning", title: "What 80/20 running means and what it does not", html: `<p>“80/20” is shorthand for organizing most endurance training at low intensity while reserving a smaller share for purposeful harder work. It is not a requirement that every runner record exactly 80.0% easy and 20.0% hard every week. Published training-intensity distributions vary by sport, athlete level, season and counting method.</p><p>The useful principle is separation: easy training should be sustainable enough to support consistency, while hard training should have a clear purpose. The ratio becomes harmful when it is treated as permission to increase intensity, a diagnostic score or proof that total volume is appropriate.</p>` },
      { id: "definitions", title: "Define the zones before calculating the split", html: `<p>Much of the training-distribution literature uses a three-zone physiological model. Zone 1 sits below the first lactate or ventilatory threshold; Zone 2 lies between the first and second thresholds; Zone 3 is above the second threshold. A consumer watch's five colored heart-rate zones are not automatically equivalent.</p><table><thead><tr><th>Three-zone model</th><th>Practical description</th><th>Common mapping error</th></tr></thead><tbody><tr><td>Zone 1: low</td><td>Below first threshold, usually conversational</td><td>Assuming it means only watch HR Zone 1</td></tr><tr><td>Zone 2: moderate</td><td>Between first and second thresholds</td><td>Calling all steady running “easy”</td></tr><tr><td>Zone 3: high</td><td>Above second threshold</td><td>Counting only maximal intervals as hard</td></tr></tbody></table><p>Laboratory testing can locate thresholds more directly, but field estimates can still be useful when applied consistently. Talk test, race history and heart-rate response provide context; none makes the boundary perfectly precise.</p>` },
      { id: "time-or-sessions", title: "Time in zone and session goal answer different questions", html: `<p>Researchers may describe distribution by accumulated time, by the main goal of each session or by intervals completed. These methods can produce different ratios from the same week. A workout containing 25 hard minutes plus 50 minutes of warm-up, recovery and cooldown is one hard session but mostly low-intensity time.</p><p>RunAnalytics uses <strong>time in zone</strong> because activity streams provide duration samples. The result should not be compared directly with a study that classified whole sessions. Heart-rate lag also means short intervals may spend less recorded time in the highest zone than the actual metabolic demand suggests.</p>` },
      { id: "research", title: "What the research supports", html: `<p>A 2015 focused review by Stöggl and Sperlich found that most descriptive studies of well-trained and elite endurance athletes showed a pyramidal distribution, while some athletes used polarized structures during particular phases. Their earlier nine-week randomized study of 48 well-trained endurance athletes reported larger improvements in several measured variables in the polarized group than in threshold, high-intensity-only or high-volume groups.</p><p>That trial is informative but not universal: it combined runners, cyclists, triathletes and cross-country skiers, involved well-trained athletes and lasted nine weeks. A later study in recreational runners found focused endurance training achieved similar improvements to polarized training with less total training time. Taken together, the literature supports prioritizing low intensity and questions excessive threshold work; it does not establish one winning ratio for every recreational runner.</p>` },
      { id: "patterns", title: "Polarized, pyramidal and threshold-heavy patterns", html: `<table><thead><tr><th>Pattern</th><th>Shape</th><th>When it may appear</th><th>Main caution</th></tr></thead><tbody><tr><td>Polarized</td><td>Much low, little moderate, distinct high</td><td>Blocks emphasizing clear easy/hard separation</td><td>Hard share can be misread as a target to add</td></tr><tr><td>Pyramidal</td><td>Much low, some moderate, less high</td><td>Many endurance plans and race-specific phases</td><td>Moderate work can gradually crowd out easy running</td></tr><tr><td>Threshold-heavy</td><td>Large middle-intensity share</td><td>Unstructured “comfortably hard” running</td><td>Fatigue without enough truly easy volume</td></tr><tr><td>Mixed</td><td>No stable shape</td><td>Transition weeks, sparse data or irregular training</td><td>Ratio may not represent a coherent block</td></tr></tbody></table><p>Neither polarized nor pyramidal automatically means the runner is recovering or improving. Distribution describes composition, not the appropriateness of the total load.</p>` },
      { id: "worked-example", title: "Worked example: normalize the period correctly", html: `<p>A runner records 1,440 low-intensity minutes, 300 moderate minutes and 180 high-intensity minutes over 42 days. Total time is 1,920 minutes: 75% low, 15.6% moderate and 9.4% high. Because 42 days equals six weeks, the weekly average is <strong>320 minutes</strong>, not 1,920 minutes.</p><p>If the moderate share is judged excessive for the block, the first recommendation should redistribute some current minutes toward easy running. Automatically adding high-intensity minutes would increase total stress while claiming to “fix” the percentages.</p>` },
      { id: "analyze", title: "How to calculate your real distribution", html: `<ol><li>Choose a stable 28–42 day window rather than one unusual week.</li><li>Confirm threshold definitions and inspect missing heart-rate data.</li><li>Include warm-ups and cooldowns consistently.</li><li>Normalize totals into minutes per week.</li><li>Review both percentages and absolute minutes.</li></ol><p>The <a href="/tools/training-split-analyzer">Training Split Analyzer</a> performs those calculations and protects against recommending additional hard minutes solely to match a template. Compare the result with long-run durability using the <a href="/blog/heart-rate-drift-aerobic-decoupling">aerobic-decoupling guide</a> and with pace targets using the <a href="/tools/training-pace-calculator">Training Pace Calculator</a>.</p>` },
      { id: "misleading", title: "When the ratio is misleading", html: `<ul><li><strong>Incorrect thresholds:</strong> easy time is assigned to the middle zone.</li><li><strong>Short intervals:</strong> heart rate rises too slowly to capture the work.</li><li><strong>Cross-training:</strong> cycling and running heart-rate responses are merged without context.</li><li><strong>Incomplete data:</strong> runs without heart rate disappear from the distribution.</li><li><strong>Recovery week:</strong> a small denominator makes one workout dominate the percentage.</li><li><strong>Race week:</strong> competition is analyzed as if it were normal training composition.</li></ul><p>Cadence, pace and heart rate are all context-dependent. The <a href="/blog/running-cadence-by-pace">cadence-by-pace guide</a> provides a similar example of why one population target should not replace within-runner comparisons.</p>` },
      { id: "apply", title: "Use the split as a decision guardrail", html: `<p>Ask whether the current distribution supports the block's purpose and whether the runner can recover from it. For a threshold-heavy pattern, make easy days easier before adding harder sessions. For a balanced pattern with rising fatigue, reduce total load rather than preserving percentages at all costs.</p><p>A good-looking percentage can still hide the wrong workload. Eighty percent of a sudden mileage jump may be excessive, while one short workout can make an appropriate recovery week look aggressive. Place the split beside total minutes, recent progression, long-run duration, rest days, sleep and the runner's response. Do not add easy mileage merely to dilute the hard percentage: the goal is a recoverable dose, not a prettier ratio.</p><p>Review the distribution every four to six weeks, not after every run. Pain, illness and persistent unusual fatigue should override a target ratio and receive appropriate attention.</p>` },
    ],
    faqs: [
      { question: "Must every week be exactly 80/20?", answer: "No. Treat the ratio as a broad guardrail across a training block, not a pass/fail target for every week." },
      { question: "Is polarized better than pyramidal training?", answer: "Both can be reasonable. The appropriate distribution depends on the runner, event, training phase and zone definitions." },
      { question: "Should threshold-heavy runners add more hard training?", answer: "Usually the first adjustment is to reduce or redistribute moderate intensity, not automatically increase hard minutes or total load." },
      { question: "Should I count sessions or minutes?", answer: "Either can describe training, but do not compare methods as though they are identical. RunAnalytics uses time in zone and reports normalized weekly minutes." },
      { question: "Can watch heart-rate zones calculate 80/20 accurately?", answer: "Only if the zone boundaries correspond reasonably to your physiological thresholds and the stream is complete. Default device zones often need review." },
    ],
    sources: [
      { label: "RunAnalytics Training Split Analyzer", href: "/tools/training-split-analyzer" },
      { label: "Stöggl & Sperlich (2015): Training-intensity distribution focused review", href: "https://www.frontiersin.org/journals/physiology/articles/10.3389/fphys.2015.00295/full" },
      { label: "Stöggl & Sperlich (2014): Polarized versus threshold, HIIT and high-volume training", href: "https://www.frontiersin.org/journals/physiology/articles/10.3389/fphys.2014.00033/full" },
      { label: "Festa et al. (2019): Intensity distribution in recreational runners", href: "https://www.frontiersin.org/journals/sports-and-active-living/articles/10.3389/fspor.2019.00070/full" },
      { label: "Related guide: Running cadence in pace context", href: "/blog/running-cadence-by-pace" },
    ],
  },
  {
    slug: "marathon-fueling-calculator-guide",
    title: "Marathon Fueling Calculator Guide: Build a Race Plan",
    description: "Build a marathon carbohydrate, gel, sodium and fluid schedule, and learn how to test tolerance before race day.",
    date: "2026-08-07",
    dateLabel: "August 7, 2026",
    readTime: "10 min read",
    category: "Race Preparation",
    topic: "training",
    lede: "A fueling calculator organizes a plan; it does not prove that your gut can tolerate it. The most reliable strategy is specific, counts every carbohydrate source and has been rehearsed in long runs.",
    sections: [
      { id: "evidence", title: "What a fueling calculator can and cannot decide", html: `<p>Sports-nutrition guidance supports carbohydrate during prolonged endurance exercise, but the target depends on duration, intensity, product mix and gastrointestinal tolerance. The 2016 joint position statement from the Academy of Nutrition and Dietetics, Dietitians of Canada and ACSM emphasizes individualized nutrition strategies and referral to a credentialed sports dietitian when a personalized plan is needed.</p><p>A calculator can convert a chosen grams-per-hour target into servings and times. It cannot measure carbohydrate absorption, sweat rate, sodium concentration, medical risk or whether a product will be tolerated at marathon intensity. The output is a draft for rehearsal, not a prescription.</p>` },
      { id: "inputs", title: "Start with expected duration, not just distance", html: `<p>Two marathoners cover 42.195 km but may spend three or six hours on course. Duration determines total carbohydrate and the number of opportunities to consume it. Start with a realistic goal range from the <a href="/tools/race-predictor">Race Predictor</a>, then build exact checkpoints with the <a href="/tools/race-split-calculator">Race Split Calculator</a>.</p><p>Also record aid-station spacing, whether the course supplies your practiced product, expected weather and what you can carry. A theoretically perfect schedule that cannot be executed at course checkpoints is not useful.</p>` },
      { id: "carbohydrate-target", title: "Choose a carbohydrate target you can justify", html: `<p>Guidance commonly scales intake with event duration. For prolonged events, 30–60 g/hour is a familiar range, while intakes approaching 90 g/hour may be used in longer events with appropriate carbohydrate mixtures and prior gut training. “Up to” is not “required.” A runner tolerating 45 g/hour should not jump to 90 on race morning because a table shows the upper end.</p><table><thead><tr><th>Current evidence and experience</th><th>Planning approach</th></tr></thead><tbody><tr><td>No intake practice</td><td>Begin during training with a modest, tolerable amount</td></tr><tr><td>Comfortable near 30–45 g/hour</td><td>Repeat consistently before increasing</td></tr><tr><td>Comfortable near 60 g/hour</td><td>Test the exact race product and concentration</td></tr><tr><td>Considering higher intake</td><td>Progress gradually and consider qualified sports-nutrition support</td></tr></tbody></table><p>Higher targets can require multiple transportable carbohydrate sources and careful concentration. Product marketing should not replace tolerance evidence.</p>` },
      { id: "carbohydrate", title: "Count every carbohydrate source", html: `<p>Gels are only one source. Drink mix, chews, bars, bananas and aid-station food all contribute. Read the label per serving rather than assuming every gel contains the same amount.</p><p>Use this equation:</p><p><strong>Total carbohydrate required = target grams/hour × expected race hours</strong></p><p><strong>Carbohydrate per hour = gels + drink mix + chews + food consumed in that hour</strong></p><p>A common calculation error is to plan 60 g/hour from gels and then add a carbohydrate drink without counting it, unintentionally raising both carbohydrate concentration and gastrointestinal load.</p>` },
      { id: "worked-example", title: "Worked example: a four-hour marathon", html: `<p>A runner has repeatedly tolerated 60 g/hour during long runs. Across four hours, the draft target is 240 g. Their gel contains 25 g and their planned drink intake supplies about 20 g/hour.</p><p>If they take one gel every 40 minutes, that is six gels across four hours, or 150 g. Drink contributes about 80 g, bringing the total to 230 g, approximately 57.5 g/hour. That is close enough to the practiced target without inventing a final gel simply to hit an exact number.</p><p>The schedule must then be aligned with water access and the product instructions. If the weather changes drink consumption, carbohydrate from the drink also changes; the plan needs a contingency.</p>` },
      { id: "schedule", title: "Turn the target into an executable schedule", html: `<p>The <a href="/tools/marathon-fueling">Marathon Fueling Planner</a> divides the selected target into servings and intervals. A useful schedule states what, when and how, not just a total:</p><ul><li>Begin early enough that intake is distributed rather than back-loaded.</li><li>Coordinate products requiring water with aid stations.</li><li>Avoid stacking multiple concentrated products at once.</li><li>Carry a small contingency without planning to consume it automatically.</li><li>Use elapsed time or course landmarks that remain understandable under fatigue.</li></ul><p>Print or copy the plan, but keep it simple. Six reliable actions are better than a spreadsheet the runner cannot follow.</p>` },
      { id: "gut-training", title: "Gut training is part of marathon training", html: `<p>The gastrointestinal tract adapts to repeated feeding exposure. Jeukendrup's review describes changes in comfort, gastric handling and carbohydrate absorption with nutritional training. A 2023 systematic review found possible benefits for discomfort and malabsorption, while also noting heterogeneous protocols and inconclusive outcomes in several studies.</p><p>Use long runs to rehearse the exact product, dose, concentration, timing and carrying method. Progress one variable at a time over several exposures. Record nausea, bloating, reflux, cramping, urgency and unused fuel. If symptoms increase, reduce complexity and identify the trigger instead of forcing the planned number.</p>` },
      { id: "sodium-fluid", title: "Separate carbohydrate planning from hydration claims", html: `<p>Fluid and sodium needs vary with sweat rate, climate, pace, body size and event duration. A calculator that does not measure those variables cannot prescribe one safe sodium number. Sodium does not make unlimited fluid intake safe.</p><p>The international exercise-associated hyponatremia consensus identifies excessive hypotonic fluid consumption as the principal cause of dilutional exercise-associated hyponatremia and supports thirst-guided drinking as a strategy to reduce overdrinking. Symptoms such as confusion, severe headache, repeated vomiting, seizures or altered mental status require urgent medical care, not an online calculator.</p><p>Test fluid access in expected conditions and avoid finishing heavier than the start because of excessive drinking. Runners with medical conditions or medication affecting fluid/electrolyte balance should obtain individualized professional advice.</p>` },
      { id: "contingencies", title: "Build race-day contingencies", html: `<table><thead><tr><th>Problem</th><th>Prepared response</th></tr></thead><tbody><tr><td>Missed gel</td><td>Resume the schedule; do not double the next dose automatically</td></tr><tr><td>Drink mix unavailable</td><td>Know the carbohydrate content of the backup product</td></tr><tr><td>GI discomfort</td><td>Reduce concentration or pause intake according to the strategy rehearsed in training</td></tr><tr><td>Hotter conditions</td><td>Adjust pace and fluid access; do not let drink carbohydrate rise unnoticed</td></tr><tr><td>Slower finish time</td><td>Carry or identify enough fuel for the longer duration</td></tr></tbody></table>` },
      { id: "rehearsal", title: "Final rehearsal checklist", html: `<ul><li>Goal-time range and course checkpoints are realistic.</li><li>Every carbohydrate source is counted.</li><li>The target has been tolerated repeatedly at a similar effort.</li><li>Gel timing matches water availability.</li><li>Drink concentration has been measured, not guessed.</li><li>A slower-race contingency is available.</li><li>No product or aggressive target is new on race day.</li></ul><p>Fueling is one part of preparation. Review whether the broader training structure is sustainable in the <a href="/blog/80-20-running-training-split">80/20 training guide</a>, and compare automated guidance with static and human support in the <a href="/blog/ai-running-coach-vs-training-plan">AI coach comparison</a>.</p>` },
    ],
    faqs: [
      { question: "How many gels are needed for a marathon?", answer: "It depends on course time, carbohydrate per gel and carbohydrate from drinks or food. Calculate grams per hour rather than relying on a universal gel count." },
      { question: "When should fueling begin?", answer: "Most plans begin early enough to avoid playing catch-up. The exact timing should be practiced and coordinated with water when the product requires it." },
      { question: "Can a calculator determine sodium needs?", answer: "It can organize a target you choose, but individual sweat and sodium losses require context that a basic calculator does not measure." },
      { question: "Is 90 grams of carbohydrate per hour required?", answer: "No. It is an upper-range strategy used in some long events, not a universal requirement. Intake should reflect event duration, product composition and demonstrated tolerance." },
      { question: "Should I drink on a fixed schedule?", answer: "Aid-station planning is useful, but avoid drinking beyond need simply to hit a volume. The hyponatremia consensus supports thirst-guided intake to reduce overdrinking risk." },
    ],
    sources: [
      { label: "RunAnalytics Marathon Fueling Planner", href: "/tools/marathon-fueling" },
      { label: "Thomas, Erdman & Burke (2016): Nutrition and Athletic Performance position statement", href: "https://pubmed.ncbi.nlm.nih.gov/26891166/" },
      { label: "Jeukendrup (2017): Training the gut for athletes", href: "https://pubmed.ncbi.nlm.nih.gov/28332114/" },
      { label: "King et al. (2023): Gut-training systematic review", href: "https://pubmed.ncbi.nlm.nih.gov/37061651/" },
      { label: "Hew-Butler et al. (2015): Exercise-associated hyponatremia consensus", href: "https://bjsm.bmj.com/content/49/22/1432" },
      { label: "Australian Institute of Sport carbohydrate guidance", href: "https://www.ais.gov.au/__data/assets/pdf_file/0011/999119/36194_Sport-supplement-fact-sheets-Sports-confectionery-v4.pdf" },
      { label: "Related guide: Calculate your actual training split", href: "/blog/80-20-running-training-split" },
    ],
  },
  {
    slug: "ai-running-coach-vs-training-plan",
    title: "AI Running Coach vs Static Training Plan",
    description: "Compare AI coaching, fixed training plans and human coaching by adaptability, context, accountability, cost and limitations.",
    date: "2026-08-07",
    dateLabel: "August 7, 2026",
    readTime: "10 min read",
    category: "AI & Technology",
    topic: "ai",
    lede: "A static plan provides structure. An AI coach can respond to recorded training. A human coach can ask about context that sensors never capture. The right choice depends on the decision you need help making.",
    sections: [
      { id: "definitions", title: "Three products that are often called a training plan", html: `<p>A PDF schedule, an adaptive rules engine and a conversational AI coach may all be marketed as “personalized,” but they perform different jobs.</p><table><thead><tr><th>Option</th><th>What changes</th><th>What usually stays fixed</th></tr></thead><tbody><tr><td>Static plan</td><td>The runner chooses a level or goal</td><td>Weekly structure after download</td></tr><tr><td>Adaptive plan</td><td>Future sessions respond to recorded completion or rules</td><td>The underlying progression framework</td></tr><tr><td>AI coaching layer</td><td>Explanations and suggestions respond to data and questions</td><td>Its access to unrecorded human context</td></tr></tbody></table><p>Before comparing products, identify which of those functions is actually required. A runner who only needs a sensible 10K schedule may gain little from continuous analysis; a runner with a changing work calendar may value adaptation more than additional metrics.</p>` },
      { id: "research", title: "What research on digital coaching can support", html: `<p>Evidence about digital physical-activity interventions is broader than evidence about AI-generated running plans. A 2018 systematic review and meta-analysis of 18 randomized trials found small-to-moderate improvements in physical activity from wearable and smartphone interventions, with substantial heterogeneity. A 2025 meta-analysis of standalone digital behavior-change interventions reported a statistically significant but small effect with low-certainty evidence for physical activity.</p><p>Those findings do <strong>not</strong> prove that an AI running coach improves race performance, prevents injury or outperforms a qualified human coach. Many interventions combine reminders, goal setting, feedback and self-monitoring. The active ingredient may be adherence support rather than algorithmic intelligence.</p><p>A 2025 review of smartwatch-assisted machine-learning exercise systems found strong laboratory performance for some recognition tasks but limited external validity, narrow demographic representation and relatively little longitudinal or explainable-AI evaluation. This is exactly why a product should disclose what evidence comes from the runner's data and what remains an inference.</p>` },
      { id: "static", title: "What a static plan does well", html: `<p>A well-designed fixed plan is predictable, inexpensive and easy to audit. The runner can see the entire progression, move sessions around cautiously and understand what happens next. Static does not mean unscientific; many successful plans use stable training principles.</p><p>It works best when the runner begins near the assumed fitness and volume, has a stable schedule and can make sensible adjustments. Its main weakness is not the lack of daily novelty. It is that missed weeks, illness, unexpected races or a major change in availability require human judgment.</p><p>Use the <a href="/blog/80-20-running-training-split">training-intensity distribution guide</a> to check whether the plan protects easy running, and the <a href="/tools/training-pace-calculator">Training Pace Calculator</a> to avoid using stale workout targets.</p>` },
      { id: "ai", title: "What an AI coach can adapt", html: `<p>An AI system can summarize synced activities, compare recent periods and connect a suggestion to recorded pace, heart rate, cadence, elevation and completion history. It can reduce the work required to find patterns across many runs and can explain a calculation in everyday language.</p><p>RunAnalytics provides a <a href="/ai-agent-coach">Premium Preview</a> so a runner can inspect the style of analysis before starting a trial. A useful preview should identify the specific run and evidence used, state what is missing, and recommend one proportionate next step.</p><p>Adaptation is only as good as the input. If an activity is missing, heart rate is inaccurate or the runner completed an unrecorded workout, the system sees an incomplete week. It cannot infer pain, illness, sleep, medication, pregnancy, life stress or motivation unless that context is explicitly and appropriately supplied.</p>` },
      { id: "data-quality", title: "The data-quality chain behind personalization", html: `<ol><li><strong>Collection:</strong> the watch records GPS, time and optional sensors.</li><li><strong>Transfer:</strong> the source platform exposes fields and streams through its API.</li><li><strong>Normalization:</strong> units, cadence semantics and missing samples are handled consistently.</li><li><strong>Analysis:</strong> comparable periods and transparent formulas are selected.</li><li><strong>Recommendation:</strong> the system distinguishes evidence from inference.</li></ol><p>An error at the first three steps can produce confident but incorrect coaching at the fifth. The <a href="/blog/heart-rate-drift-aerobic-decoupling">heart-rate drift guide</a> and <a href="/blog/running-cadence-by-pace">cadence guide</a> show how heat, terrain, pace and device semantics change apparently simple metrics.</p>` },
      { id: "human", title: "Where a human coach remains different", html: `<p>A qualified human coach can observe behavior, ask follow-up questions, notice ambiguity and build accountability through a relationship. They can integrate family demands, fear, motivation, race experience and subtle communication that is not stored in an activity file.</p><p>Human coaching quality, availability and cost vary, and a coach can also make mistakes. The appropriate comparison is not “human good, AI bad.” It is whether the support channel has enough context, relevant competence and a feedback loop for the decision at hand.</p><p>Recurring pain, disordered eating concerns, complex medical context and rehabilitation decisions require appropriately qualified human care. AI output should not be represented as diagnosis or clinical clearance.</p>` },
      { id: "comparison", title: "Choose by the decision, not the label", html: `<table><thead><tr><th>Need</th><th>Best starting option</th><th>Why</th></tr></thead><tbody><tr><td>Simple race structure and stable schedule</td><td>Static plan</td><td>Low complexity and full visibility</td></tr><tr><td>Schedule changes and missed sessions</td><td>Adaptive plan</td><td>Rules can move future work without stacking it</td></tr><tr><td>Frequent explanations from recorded runs</td><td>AI coaching layer</td><td>Fast summaries and pattern retrieval</td></tr><tr><td>Complex context or high accountability</td><td>Qualified human coach</td><td>Conversation, observation and relationship</td></tr><tr><td>Data summaries for an existing coach</td><td>AI plus human</td><td>Automation supports, not replaces; judgment</td></tr></tbody></table>` },
      { id: "evaluation", title: "A seven-question product evaluation", html: `<ol><li><strong>Which data is used?</strong> Look for exact fields and time windows.</li><li><strong>How is missing data handled?</strong> Silence is better than invented certainty.</li><li><strong>Can recommendations explain their evidence?</strong> A number without provenance is hard to trust.</li><li><strong>Does it separate coaching from medical claims?</strong> Avoid injury-prevention guarantees.</li><li><strong>Can you correct context?</strong> Travel, illness and schedule changes should be expressible.</li><li><strong>What happens to your data?</strong> Review authorization, retention and deletion controls.</li><li><strong>Can you evaluate value before paying?</strong> Pricing, trial terms and cancellation should be visible.</li></ol>` },
      { id: "red-flags", title: "Marketing and coaching red flags", html: `<ul><li>Guaranteed race times or calibrated confidence without validation.</li><li>Claims to diagnose or prevent injury from training data alone.</li><li>Universal cadence, heart-rate or mileage targets presented as personalization.</li><li>Recommendations that stack missed hard sessions.</li><li>No explanation of missing sensor data.</li><li>“AI” used as the only description of methodology.</li><li>A trial or cancellation flow that hides the terms.</li></ul><p>Good coaching can be conservative. “The data is insufficient” is sometimes the most trustworthy result.</p>` },
      { id: "workflow", title: "A practical hybrid workflow", html: `<p>Use a static or adaptive plan for structure, public tools for transparent calculations and an AI layer for rapid review. Bring recurring uncertainty, symptoms or important performance decisions to a qualified human. For example:</p><ol><li>Set a realistic goal and plan structure.</li><li>After a long run, review fueling with the <a href="/blog/marathon-fueling-calculator-guide">marathon fueling guide</a>.</li><li>Use AI to summarize what changed and list missing context.</li><li>Accept or reject the suggestion based on symptoms, schedule and professional advice.</li><li>Review trends across several weeks rather than reacting to every run.</li></ol>` },
      { id: "evaluate", title: "Evaluate RunAnalytics before paying", html: `<p>Inspect the Premium Preview, confirm which activity supports each finding and read the <a href="/faq">methodology and limitations</a>. Compare the recommendation with your own knowledge, and never treat it as medical diagnosis.</p><p>Read the <a href="/blog/ai-running-coach-complete-guide-2026">complete AI running coach guide</a> and inspect the <a href="/pricing">current plan details</a>, trial terms and cancellation path before starting.</p>` },
    ],
    faqs: [
      { question: "Can an AI coach replace a human coach?", answer: "It can automate analysis and routine feedback, but it cannot fully replace observation, relationship, judgment and context supplied to a qualified human coach." },
      { question: "Is a static plan bad because it does not adapt?", answer: "No. A suitable static plan can provide excellent structure. The runner must know when and how to adjust it." },
      { question: "What data can an AI running coach use?", answer: "Depending on the product and device, it may use pace, distance, heart rate, cadence, elevation, training history, goals and information the runner explicitly provides. Missing or inaccurate inputs weaken the result." },
      { question: "Is there research proving AI running coaches improve race performance?", answer: "The broader digital-intervention literature supports modest physical-activity effects in some settings, but it does not establish that every AI running coach improves race performance or outperforms human coaching." },
      { question: "What should an AI recommendation explain?", answer: "It should identify the activities and metrics used, state missing context, distinguish observation from inference and offer a proportionate action." },
    ],
    sources: [
      { label: "RunAnalytics methodology and limitations", href: "/faq" },
      { label: "Gal et al. (2018): Wearable and smartphone intervention meta-analysis", href: "https://pubmed.ncbi.nlm.nih.gov/30178072/" },
      { label: "Lee & Park (2025): Standalone digital behavior-change meta-analysis", href: "https://pubmed.ncbi.nlm.nih.gov/40659761/" },
      { label: "Monteiro-Guerra et al. (2020): Personalization in real-time mobile coaching", href: "https://pubmed.ncbi.nlm.nih.gov/31751254/" },
      { label: "Jubair & Mehenaz (2025): Smartwatch-assisted ML exercise prescription review", href: "https://pubmed.ncbi.nlm.nih.gov/40918076/" },
      { label: "Strava API agreement", href: "https://www.strava.com/legal/api" },
      { label: "Related guide: Marathon fueling calculator methodology", href: "/blog/marathon-fueling-calculator-guide" },
    ],
  },
];

export function getEditorialPost(slug: string): EditorialPost | undefined {
  return editorialPosts.find((post) => post.slug === slug);
}
