import React from 'react';
import {Activity,ArrowRight,AudioLines,BarChart3,Bell,CalendarDays,Check,ChevronDown,Mic,ShieldCheck,Smartphone,Tablet} from 'lucide-react';
import {iosAppFaqs,iosPrivacySections} from './iosAppContent';

function Shell({children}:{children:React.ReactNode}){
 return <div className="ios-site"><link rel="stylesheet" href="/ios-app/landing-v1.css" />
  <a className="ios-skip" href="#ios-main">Skip to content</a>
  <header className="ios-nav"><div className="ios-container ios-nav-inner">
   <a className="ios-brand" href="/" aria-label="RunAnalytics home"><span><Activity aria-hidden="true" size={23}/></span>RunAnalytics</a>
   <nav aria-label="App navigation"><a href="/ios-app#features">The app</a><a href="/ios-app#ipad">For iPad</a><a href="/ios-app#pricing">Pricing</a><a href="/ios-app/privacy">Privacy</a></nav>
   <span className="ios-status"><span/>Coming Soon</span>
  </div></header>
  {children}
  <footer className="ios-footer"><div className="ios-container"><a className="ios-brand" href="/"><span><Activity size={20} aria-hidden="true"/></span>RunAnalytics</a><p>Your running, in focus.</p><nav aria-label="Footer"><a href="/ios-app">iPhone &amp; iPad</a><a href="/ios-app#pricing">Pricing</a><a href="/ios-app/privacy">App privacy</a><a href="/privacy">Privacy policy</a><a href="/terms">Terms</a><a href="mailto:hello@aitracker.run">Contact</a><a href="/proactive-running-coach">WhatsApp coach</a></nav><small>© 2026 RunAnalytics. iPhone and iPad are trademarks of Apple Inc. Strava is a separate service.</small></div></footer>
 </div>;
}
function Shot({name,alt,tablet=false,eager=false}:{name:string;alt:string;tablet?:boolean;eager?:boolean}){
 return <img className={tablet?'ios-tablet-shot':'ios-phone-shot'} src={`/ios-app/${name}-v1.webp`} alt={alt} width={tablet?1440:600} height={tablet?993:1304} loading={eager?'eager':'lazy'} decoding="async" {...(eager?{fetchpriority:'high'}:{})}/>;
}
export function IosAppContent(){return <Shell><main id="ios-main">
 <section className="ios-hero"><div className="ios-container ios-hero-grid"><div className="ios-hero-copy">
  <p className="ios-eyebrow"><Smartphone size={16} aria-hidden="true"/> Made for iPhone &amp; iPad</p>
  <h1>Your running.<br/>Your coach.<br/><em>Right here.</em></h1>
  <p className="ios-lede">Turn the runs you’ve done into a clearer idea of what comes next. Talk it through, follow your plan, and see your progress—all in one native app.</p>
  <div className="ios-actions"><a className="ios-button" href="#features">Meet your running companion <ArrowRight size={18} aria-hidden="true"/></a></div>
  <p className="ios-launch"><span/>Coming Soon on iPhone and iPad</p>
  <p className="ios-hero-pricing"><a href="#pricing">7-day free trial · From $7.99/month</a><span>For eligible new subscribers. Cancel anytime.</span></p>
  <div className="ios-hero-details"><span><Check size={15} aria-hidden="true"/>Your existing RunAnalytics account</span><span><Check size={15} aria-hidden="true"/>Your Strava running history</span></div>
 </div><div className="ios-hero-art"><div className="ios-orbit"/><div className="ios-device"><Shot name="coach" eager alt="Actual Run Analytics iPhone coach screen with voice controls and a conversation about adapting an easy run"/></div><div className="ios-art-note"><AudioLines size={25} aria-hidden="true"/><div><strong>A conversation. Not another chart.</strong><span>Voice + chat, with your training in context.</span></div></div></div></div></section>
 <div className="ios-feature-rail ios-container" aria-label="App highlights">{[[Mic,'Talk naturally'],[CalendarDays,'Know what’s next'],[BarChart3,'See your progress'],[Bell,'Stay in the loop']].map(([Icon,label])=>{const I=Icon as typeof Mic;return <div key={String(label)}><I size={21} aria-hidden="true"/><span>{String(label)}</span></div>;})}</div>
 <section id="features" className="ios-section ios-container"><div className="ios-section-heading"><p className="ios-eyebrow">01 / A coach who has the context</p><h2>Less explaining.<br/>More understanding.</h2><p>Your recent runs, saved plan and goals give the conversation a starting point. Ask a quick question in chat, or talk to your coach when typing gets in the way.</p></div>
  <div className="ios-conversation-grid"><article className="ios-prompt-card"><Mic aria-hidden="true"/><h3>“How does this run fit my week?”</h3><p>Connect today’s effort to recent training, recovery signals and the sessions ahead.</p></article><article className="ios-prompt-card"><CalendarDays aria-hidden="true"/><h3>“I only have 30 minutes today.”</h3><p>Talk through a practical change. Review the proposed plan adjustment before anything is saved.</p></article><article className="ios-prompt-card"><Activity aria-hidden="true"/><h3>“Help me understand that run.”</h3><p>Open a past run and bring it straight into the coach conversation—without retyping your stats.</p></article></div>
 </section>
 <section className="ios-plan-section"><div className="ios-container ios-split"><div className="ios-plan-art"><div className="ios-plan-ring"/><div className="ios-device"><Shot name="plan" alt="Actual training-plan screen showing today’s easy run, tomorrow’s long run and a rest day"/></div></div><div className="ios-section-heading"><p className="ios-eyebrow">02 / Your plan, at a glance</p><h2>A little structure.<br/><em>A lot of possibility.</em></h2><p>Open your plan to today and what’s next. See the purpose, duration and distance of each session, with recovery days right where they belong.</p><ul className="ios-check-list"><li><Check/>Upcoming workouts, not a week of already-past days</li><li><Check/>Your goals and training schedule in one place</li><li><Check/>Coach-assisted plan reviews, with you in control</li></ul><p className="ios-fineprint">Plan creation and changes require eligible coaching access and explicit confirmation. Access may be limited during rollout.</p></div></div></section>
 <section id="progress" className="ios-section ios-container"><div className="ios-section-heading ios-centered"><p className="ios-eyebrow">03 / Every run tells part of the story</p><h2>See the bigger picture.</h2><p>Not just how far you ran. How your running is adding up.</p></div><div className="ios-progress-grid">
  <article><div className="ios-progress-copy"><span>01</span><h3>Miles with meaning</h3><p>Weekly and monthly mileage charts make your training rhythm easier to see.</p></div><Shot name="mileage" alt="Native progress screen showing weekly running distance as a bar chart"/></article>
  <article><div className="ios-progress-copy"><span>02</span><h3>Consistency you can see</h3><p>Explore your activity calendar and tap a day to revisit its runs.</p></div><Shot name="calendar" alt="GitHub-style running activity calendar with weeks in columns and a linked run"/></article>
  <article><div className="ios-progress-copy"><span>03</span><h3>Insights, not guesswork</h3><p>Read saved coach insights alongside training-load and recovery signals.</p></div><Shot name="insights" alt="Native coach insights screen showing recovery and training load from demo running data"/></article>
 </div><div className="ios-progress-extra"><Activity aria-hidden="true"/><p><strong>Go deeper into any run.</strong> Distance, pace, heart rate, elevation, recorded laps and route maps when available. Track your overall Runner Score and explore race estimates, too.</p></div></section>
 <section id="ipad" className="ios-ipad-section"><div className="ios-container"><div className="ios-ipad-heading"><div><p className="ios-eyebrow"><Tablet size={17} aria-hidden="true"/> Built for the bigger screen</p><h2>More room<br/>for your next chapter.</h2></div><p>On iPad, a native sidebar keeps Coach, Plan, Progress and Settings close. Settle in, look at the week ahead, and give your training a little space.</p></div><div className="ios-ipad-frame"><Shot tablet name="ipad" alt="Run Analytics on iPad with a native sidebar and a populated half-marathon training plan"/></div><p className="ios-caption">Actual native app screenshots with illustrative demo data. Your available data and plan determine what you see.</p></div></section>
 <section className="ios-section ios-container"><div className="ios-section-heading"><p className="ios-eyebrow">One account. A more connected routine.</p><h2>From your first sign-in<br/>to your next run.</h2></div><ol className="ios-steps"><li><span>1</span><h3>Sign in with an email link</h3><p>Use your existing account, or create one in the app. No new password to remember.</p></li><li><span>2</span><h3>Bring your Strava runs</h3><p>Authorize Strava inside the app. Your synced history becomes the starting point.</p></li><li><span>3</span><h3>Make it your routine</h3><p>Choose your coaching preferences and opt in to reminders and updates. Premium access is required for paid coaching features.</p></li></ol></section>
 <section id="pricing" className="ios-pricing-section"><div className="ios-container">
  <div className="ios-section-heading ios-centered"><p className="ios-eyebrow">Simple pricing. One Premium membership.</p><h2>Try it free.<br/><em>Make every run count.</em></h2><p>Get to know your coach with a 7-day free trial. Your running history, training plans and progress—together on iPhone, iPad and the web.</p></div>
  <div className="ios-trial-highlights"><span><Check size={18} aria-hidden="true"/>7 days free</span><span><Check size={18} aria-hidden="true"/>$0 during your trial</span><span><Check size={18} aria-hidden="true"/>Cancel anytime</span></div>
  <div className="ios-price-grid">
   <article className="ios-price-card"><p className="ios-price-label">Monthly</p><h3><strong>$7.99</strong><span>/ month</span></h3><p>After your eligible 7-day free trial.</p><div className="ios-price-divider"/><p>Keep it flexible. Billed monthly, with no annual commitment.</p><span className="ios-price-availability">Coming Soon</span></article>
   <article className="ios-price-card ios-price-card-featured"><span className="ios-price-badge">Save $15.89 a year</span><p className="ios-price-label">Annual</p><h3><strong>$79.99</strong><span>/ year</span></h3><p>After your eligible 7-day free trial.</p><div className="ios-price-divider"/><p>A year of Premium, billed annually. Less than 12 monthly payments.</p><span className="ios-price-availability">Coming Soon</span></article>
  </div>
  <div className="ios-price-included"><h3>Both plans include</h3><ul><li><Check/>AI voice and chat coaching</li><li><Check/>Training plans and run insights</li><li><Check/>Runner Score and progress charts</li><li><Check/>Strava sync and optional reminders</li></ul><p>Already a paid RunAnalytics member? Sign in with the same account—no second subscription needed.</p></div>
  <div className="ios-price-terms"><h3>No upfront charge. No surprises.</h3><p>Trials are for eligible new subscribers. After 7 days, your subscription automatically renews at the selected monthly or annual price unless cancelled. For Apple subscriptions, cancel at least 24 hours before the trial or current billing period ends in Apple Settings → Subscriptions. Cancelling stops the next renewal; it does not automatically refund a paid period.</p><p>Prices shown are in USD for the US. Your App Store price, eligibility and applicable taxes are shown before you confirm. Apple purchases use your Apple account; website checkout requires a payment card and website subscriptions are managed in web billing. Deleting the app does not cancel your subscription.</p></div>
 </div></section>
 <section className="ios-privacy-strip ios-container"><ShieldCheck size={34} aria-hidden="true"/><div><h2>Your data. Clear choices.</h2><p>Microphone and notifications are optional. AI coaching uses cloud processing, not just your device. Read what’s shared and how to manage your account.</p></div><a className="ios-button ios-button-outline" href="/ios-app/privacy">App privacy, explained <ArrowRight size={17} aria-hidden="true"/></a></section>
 <section className="ios-section ios-container ios-faq"><div className="ios-section-heading"><p className="ios-eyebrow">Before you lace up</p><h2>A few good questions.</h2></div><div>{iosAppFaqs.map(f=><details key={f.question}><summary>{f.question}<ChevronDown size={19} aria-hidden="true"/></summary><p>{f.answer}</p></details>)}</div></section>
 <section className="ios-closing"><div className="ios-container"><p className="ios-eyebrow">Run Analytics for iPhone &amp; iPad</p><h2>Your next run.<br/>A clearer perspective.</h2><span className="ios-coming-large">Coming Soon</span><p>Coaching and training insights—not medical advice.<br/>An internet connection is required for AI and syncing.</p></div></section>
 </main></Shell>;}

export function IosPrivacyContent(){return <Shell><main id="ios-main" className="ios-container ios-privacy-page"><a className="ios-back" href="/ios-app">← Back to the app</a><p className="ios-eyebrow">iPhone &amp; iPad / Privacy</p><h1>Your running data,<br/><em>explained clearly.</em></h1><p className="ios-lede">Run Analytics app privacy notice</p><p>Updated September 26, 2026. This app-specific notice supplements the <a href="/privacy">RunAnalytics Privacy Policy</a>, which also applies to your account. It explains the native app’s data flows and controls; it is not a separate account or service.</p><nav className="ios-privacy-toc" aria-label="Privacy topics">{iosPrivacySections.map(s=><a key={s.id} href={'#'+s.id}>{s.title}</a>)}</nav>{iosPrivacySections.map(s=><section key={s.id} id={s.id}><h2>{s.title}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}</section>)}<section><h2>Questions or privacy requests?</h2><p>Email <a href="mailto:hello@aitracker.run">hello@aitracker.run</a>. Include the email used for your account so we can help verify the request. Do not send passwords, sign-in links or unnecessary health information.</p><a className="ios-button" href="/privacy">Read the full privacy policy <ArrowRight size={18} aria-hidden="true"/></a></section></main></Shell>;}
